### ISSUE TITLE
Limit admonition types allowed

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-sphinx-theme#10]
*from October 2021 pre-launch bug bash*

**Created by**: Lia

## Description 

There are an abundance of admonition types available by default via Sphinx (10), but to have this many loses their individual meanings. Ideally we would limit to ~3-5 of the most diverse and meaningful.

## Info

**Bug source**: *unknown*

**Browser**: *unknown*

**PR**: *none*

**Comment by melissawm** [comment]
Closing as I think there's not much to do here, but feel free to reopen otherwise.
