### ISSUE TITLE
admonition class has erroneous padding when ending with a code block

### ISSUE THREAD

**Issue by kne42** [napari/napari-sphinx-theme#100]
admonition class has erroneous padding when ending with a code block

<img width="734" alt="Screen Shot 2022-05-07 at 10 59 44 AM" src="https://user-images.githubusercontent.com/29165011/167266272-8ef7820a-a059-4839-8736-fa9aeaef6e11.png">

this was an issue that was fixed in the original react version, it had something to do with a sphinx class overriding margins or smth on `pre` classes

**Comment by psobolewskiPhD** [comment]
I assume the bug is that there isn't white margin between the code and the bottom of the box.
if so, this looks like it's still a (very minor) thing:
![image](https://github.com/napari/napari-sphinx-theme/assets/76622105/c0291d00-e412-4031-a875-3cd39215acd6)
