### ISSUE TITLE
Videos are not resized to fit horizontally

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari-sphinx-theme#109]
Unlike image elements, videos are not resized to fit in the horizontal space of the main body. For example, here's a page from napari.org that spills over ands a horizontal scroll bar:

![Screen Shot 2022-06-06 at 1 31 48 PM](https://user-images.githubusercontent.com/2608297/172244600-d2b18f72-aa6f-43bb-9983-ef280f76bcc7.png)

I would expect videos to be automatically resized to fit in the main body, while maintaining the aspect ratio of the video. If the original video is smaller than the current width, not resizing and centering may be preferable to upsampling the video to stretch across the whole body, but either solution should probably be fine.

**Comment by codemonkey800** [comment]
@andy-sweet thank you for reporting this. it has been fixed! please reopen if you encounter the issue again pls

https://napari.org/howtos/layers/image.html

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2176050/176551608-6499ac06-abd8-42b9-b8e3-4796aa778c5b.png">
