### ISSUE TITLE
napari logo seems to small

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-sphinx-theme#11]
*from October 2021 pre-launch bug bash*

**Created by**: Laura Marcos

## Description 

napari logo is small which will be changed but just including this a note. Thank you!

## Info

**Bug source**: *unknown*

**Browser**: all

**PR**: *none*

## Attachments

https://dl.airtable.com/.attachments/cab11c18941d4c8c50e7eaa6c262cb65/3624e158/image.png https://dl.airtable.com/.attachments/2c519aec4f18c64d54fd002847256fa3/d1ad3624/image.png

**Comment by psobolewskiPhD** [comment]
Logo is nice and big and at the top now with #134 🎉 
![image](https://github.com/napari/napari-sphinx-theme/assets/76622105/6cffc18d-3455-49f3-9e39-f747da9519cb)
