### ISSUE TITLE
Planning to keep up with pydata sphinx theme

### ISSUE THREAD

**Issue by jni** [napari/napari-sphinx-theme#113]
Hi @codemonkey800, @neuromusic, et al,

Thanks again for all your efforts with the napari sphinx theme. As I've mentioned before, I think we're in a great place with the build right now.

However, I think we discussed early on that forking the theme was a first-pass solution. Long term, it seems hard to maintain a fork forever. (Have a look at the number of PRs in the latest pydata sphinx theme [release](https://github.com/pydata/pydata-sphinx-theme/releases)!)

I think instead we should explore using pydata sphinx theme directly, then [customizing it](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/customizing.html), and for the more elaborate things such as the calendar directive, developing additional sphinx extension packages, that we would use *in addition to* sphinx pydata theme + custom CSS.

If there's any missing features in pydata sphinx theme that would block this approach, we could possibly contribute them upstream?

What do you all think? I am speaking from a position of relative ignorance as regards to the engineering effort involved, but reading the release notes of the pydata theme I see quite a few features and improvements that we could benefit from, and I see that continuing going forward, as they have built some good momentum over the past year. So I think it's worth exploring this idea!

CC @melissawm

**Comment by jni** [comment]
> For the calendar, we can definitely extract it to its own package if:
>
> 1. pip allows us to share JS and CSS files in a pip package
> 2. sphinx will allow us to use JS and CSS files from a pip package

I *think* both of those are true? I bet @tlambert03 knows for sure. A quick search didn't turn up anything definitive though!

> Hmm, I imagined the direction from here was to maintain it as our own thing, but I understand the desire to use the theme directly to get all of the contributions added to it.

A big question for me is how hard it is to merge sphinx pydata theme main with our current main. If that's basically quick and easy, then we can keep maintaining the fork. If it's a huge lift, then I don't find it sustainable given that as you point out, we have limited developer effort to apply to this.

> Unfortunately, it would mean scrapping a lot of designs we've implemented again,

Can you clarify which parts of the design require custom js rather than CSS and config customizations applied on top of pydata? Also note that there is limited support for custom js in the PyData theme, e.g. [here](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/customizing.html#define-custom-javascript-to-react-to-theme-changes).

I also wonder how much the dev tooling (as opposed to the site design) is driving the need for a fork? I agree that bringing in a big js stack is a big ask, but ultimately I think either it's a big benefit and you should be able to convince the PyData community of that benefit, or it's a minor benefit and we can get by without it. (With the caveat that there is of course some nuance — I know for sure it's hard to move communities. But in the long term, it's usually worth it compared to going it alone.)

**Comment by jni** [comment]
@codemonkey800 I think this bit from @tlambert03 is the key that I hope is feasible:

> acting as a child theme that depends on rather than forks the upstream theme.

Maybe we can keep *all* the tooling but apply the theme by *depending* on sphinx-pydata-theme?

This is Python after all. Worst case, you can depend on it, then dynamically at run time copy all the files over to our own theme's directory! 😂

**Comment by jni** [comment]
> Maybe we can keep *all* the tooling but apply the theme by *depending* on sphinx-pydata-theme?

It looks like this is not only possible but common in the ecosystem:

https://twitter.com/choldgraf/status/1564598627749830657

Note that the twitter thread was in the context of even more fantastic updates from the pydata sphinx theme. Can we bump this issue again @codemonkey800 @neuromusic?

**Comment by jni** [comment]
> It looks like this is not only possible but common in the ecosystem:

More directly: the dask theme [depends on the sphinx book theme](https://github.com/dask/dask-sphinx-theme/blob/e1e8065844c96d64c6baec9091f855dac241e947/requirements.txt) which [depends on pydata-sphinx-theme](https://github.com/executablebooks/sphinx-book-theme/blob/7fdf64b980eeb96a629c8369b004ffb02c268b96/pyproject.toml#L26).

**Comment by jni** [comment]
The matplotlib sphinx theme also depends on pydata and adds customization. I think it's gorgeous!

https://github.com/matplotlib/mpl-sphinx-theme

**Comment by Czaki** [comment]
> we could drop the react stuff from the core theme JS, but we'll need it for the calendar at least. but dropping react will require refactoring some of the templating stuff that we do like
> 
>     * [replacing the version icons](https://github.com/napari/napari-sphinx-theme/blob/a322d287543f76a1b74c163d8db4792598a6bd64/src/napari_sphinx_theme/assets/napari.tsx#L195-L295)
> 
>     * [replace sidebar icons](https://github.com/napari/napari-sphinx-theme/blob/a322d287543f76a1b74c163d8db4792598a6bd64/src/napari_sphinx_theme/assets/napari.tsx#L195-L336)
> 
>     * [fix search container](https://github.com/napari/napari-sphinx-theme/blob/a322d287543f76a1b74c163d8db4792598a6bd64/src/napari_sphinx_theme/assets/napari.tsx#L371-L401)
> 
>     * [match search results to napari design](https://github.com/napari/napari-sphinx-theme/blob/a322d287543f76a1b74c163d8db4792598a6bd64/src/napari_sphinx_theme/assets/napari.tsx#L444-L478)
> 
>     * [use napari menu icon for app bar](https://github.com/napari/napari-sphinx-theme/blob/a322d287543f76a1b74c163d8db4792598a6bd64/src/napari_sphinx_theme/assets/napari.tsx#L480-L502)
> 
>     * [render napari icons for admonition dropdowns](https://github.com/napari/napari-sphinx-theme/blob/a322d287543f76a1b74c163d8db4792598a6bd64/src/napari_sphinx_theme/assets/napari.tsx#L525-L533)
> 
> 
> a lot of these could be done with react, but it will take time to refactor, and not sure which ones are appropriate to bring back to pydata, if any.

all of this should be quickly injected as an extension of pydata theme.

**Comment by psobolewskiPhD** [comment]
Ok! this PR can now be seen in action on napari CI:
https://output.circle-artifacts.com/output/job/c9c574d3-71c6-434f-b5ab-85bdb7ff68c3/artifacts/0/docs/docs/_build/index.html?pr=267
