### ISSUE TITLE
Wording of footer

### ISSUE THREAD

**Issue by jni** [napari/napari-sphinx-theme#12]
Nice work all on napari/napari.github.io#170! I only noticed it now but just wanted to suggest changing the "brands" of things at the bottom to verbs/actions, which are more accessible to newcomers that might not know what "image.sc" or "Zulip" are. Suggestions:

- naparihub -> (Browse) Plugins
- github -> Code
- twitter -> Tweet
- image.sc -> Ask
- zulip -> Chat

**Comment by psobolewskiPhD** [comment]
Might be worth putting (some) of these icons at the top, ala pydata-sphinx docs:
![image](https://github.com/napari/napari-sphinx-theme/assets/76622105/6cbe0218-9455-4e6a-810c-6d87477bf4b8)
The footer doesn't show until you scroll all the way down.

**Comment by jni** [comment]
Yes and we should add a mastodon link! (I refuse to use the X logo, though. Happy to have a classic look with the bird. 😃)

**Comment by melissawm** [comment]
Does this look like what you folks have in mind? I kept the original labels in tooltips, just in case.

![Captura de imagem_20240715_151431](https://github.com/user-attachments/assets/9cd03183-aeef-4055-8a8f-3582315285d4)
