### ISSUE TITLE
Sphnx 5 

### ISSUE THREAD

**Issue by Czaki** [napari/napari-sphinx-theme#121]
Is there any reason why sphinx 5.x.x is blocked, or it could be simply released?

**Comment by melissawm** [comment]
Unfortunately a number of the current dependencies require Sphinx<5:

```
sphinx-panels 0.6.0 requires sphinx<5,>=2, but you have sphinx 5.1.1 which is incompatible.
sphinx-external-toc 0.3.0 requires sphinx<5,>=3, but you have sphinx 5.1.1 which is incompatible.
myst-parser 0.17.2 requires sphinx<5,>=3.1, but you have sphinx 5.1.1 which is incompatible.
myst-nb 0.15.0 requires sphinx<5,>=3.5, but you have sphinx 5.1.1 which is incompatible.
```

Not sure if they can be updated without conflict.

**Comment by Czaki** [comment]
from `sphinx-panels` there is suggested to change to `sphinx-design` as `sphinx-panels` is no longer maintained. 
https://github.com/executablebooks/sphinx-panels/issues/80
https://github.com/executablebooks/sphinx-panels#readme

for `sphinx-external-toc` there is no issue but After remove requirements of `sphinx` `<5` all tests pass. I could create PR if you think that it is worth. 

`myst-parser` in version 0.18.0 has `"sphinx>=4,<6",` in requirements. 

`myst-nb` in version 0.16.0 has `"sphinx>=4,<6",` in requirements. 

So two requirements are not a problem, one is deprecated and should be replaced, for one it looks like small PR with replace `"sphinx>=3,<5",` to `"sphinx>=3,<6",` is required.

**Comment by melissawm** [comment]
Looks reasonable to me - @codemonkey800 any thoughts?
