### ISSUE TITLE
Either provide a Dark theme or don't have advertise a dark theme

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari-sphinx-theme#124]
Related to #22
I use an extension (Noir in Safari) that darkens websites *that don't have a dark mode* to match my system settings: light during the day, dark at night.
napari.org isn't darkened by this extention, because according to the extension it provides a dark mode. But t o my eyes, it's just the light mode. So I have to either manually override each time in the evening/night or have napari.org permanently-dark which I don't want either.

**Comment by jni** [comment]
Also related to #113 😞

**Comment by melissawm** [comment]
We can track this on #22 now that we don't advertise a dark mode anymore (I believe!)

**Comment by psobolewskiPhD** [comment]
My darkening extension is still detecting a Dark theme:
<img width="353" alt="image" src="https://github.com/napari/napari-sphinx-theme/assets/76622105/c6b45719-8787-435d-ac3c-8e17cfa2d116">
so it's not darkening the page. So somewhere, something is triggering. I will look into this some more later.

**Comment by psobolewskiPhD** [comment]
I see this in my Safari dev console:
`[Log] [PST]: Changed to auto mode using the light theme. (pydata-sphinx-theme.js, line 1)`
When I load with Light system theme. With Dark system theme it's `... dark theme`
So it looks like even though we don't offer a dark theme and the controls are disabled we are in auto mode.

**Comment by melissawm** [comment]
Argh. Thanks for checking!
