### ISSUE TITLE
Have more visible "Home" link in TOC ? 

### ISSUE THREAD

**Issue by Carreau** [napari/napari-sphinx-theme#13]
I know you  can click on the napari logo on the upper left corner, but I'm not sure this is obvious, and as this is where the users lands, what do you think of adding at the top of the left Navbar a "Home" or similar link that brings back to the root ? 

Here is how it could look like.

<img width="650" alt="Screen Shot 2022-01-26 at 11 45 31" src="https://user-images.githubusercontent.com/335567/151149599-65020606-100d-48a5-b3bf-a3154a60dce5.png">

**Comment by melissawm** [comment]
I could add a "Home" item in the top navbar. Is this something we still want to do?

**Comment by psobolewskiPhD** [comment]
eh, I'm cool with the current look, which is a bit different from that verion:
<img width="455" alt="image" src="https://github.com/napari/napari-sphinx-theme/assets/76622105/f7b83464-fdb5-4692-a244-060092de4d87">

you have `napari` above search and then `home` icon next to usage.
Good 'nuff?
I'd vote to close.

**Comment by jni** [comment]
Ditto

**Comment by melissawm** [comment]
Closing, happy to revisit later. Cheers!
