### ISSUE TITLE
Calendar details view improvement suggestions

### ISSUE THREAD

**Issue by jni** [napari/napari-sphinx-theme#138]
- [ ] Ideally, it should be dismissable by clicking anywhere outside of the details box
- [ ] It should also be dismissable with Esc
- [ ] It should be centered on the page or near the click, so that one can quickly look at many events in sequence.

CC @melissawm @psobolewskiPhD 

Just implementing the easiest one of the above would be enough for a first pass. Right now, there's a lot of mousing back and forth between the calendar and the X to close the event!

**Comment by psobolewskiPhD** [comment]
The first 2 are priorities, IMO.
For me the 3rd is take it or leave it. I actually rather like the current less in the way implementation on a larger monitor--I can see the calendar and the event. On a small screen it's basically centered anyways.

Super minor thing:
the dates (e.g. `17`) and days of the week "light up" on hover, like they should do something when you click, but they don't. 

BTW: for me it shows `all times America New York` is that for everyone? I think if it could be aware of time zones it would be amazing.

**Comment by melissawm** [comment]
It is - that should be your time zone. Is it not? Maybe that's a birwser thing again?

![Screenshot_2024-01-18-17-45-00-594_org.mozilla.firefox-edit.jpg](https://github.com/napari/napari-sphinx-theme/assets/3949932/1a20f7d1-2603-4404-bf80-5455e29ab315)

**Comment by psobolewskiPhD** [comment]
Nono, sorry I wasn't clear -- it was showing me my timezone! I wasn't sure if it wasn't sure if it was showing the same times for everyone (with the message re: timezone) or actually adapting. Looks like it adapts, which is killer!
❤️

**Comment by melissawm** [comment]
The event popover looks awful on mobile because I hardcoded it to be 20% of the screen  - needs to be made responsive 😅

![Screenshot_2024-01-18-19-15-28-263_org.mozilla.firefox.jpg](https://github.com/napari/napari-sphinx-theme/assets/3949932/ed6042a6-5dcd-47dd-9063-956bc5a6db31)

**Comment by jni** [comment]
Amazing work as always @melissawm! 😍 Man I am so pumped to see this live on the stable site!
