### ISSUE TITLE
Safari: videos are a white square without controls (but can be interacted with)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari-sphinx-theme#140]
This is how videos look on Safari after #134 
<img width="1390" alt="image" src="https://github.com/napari/napari-sphinx-theme/assets/76622105/fe5e8d18-4477-4f2a-8f37-e84383f455d7">
Right-click lets me show controls and the video plays just fine.

Here's stable docs:
<img width="1390" alt="image" src="https://github.com/napari/napari-sphinx-theme/assets/76622105/7a3c34b7-b644-4b20-806f-b79e318bc040">
The video is also white, but clear there is something there to interact with.

**Comment by jni** [comment]
@psobolewskiPhD have you tried looking at napari/docs#298 with the new theme? (ie will this issue just go away if we have fallback videos?)

**Comment by psobolewskiPhD** [comment]
yes! https://github.com/napari/docs/pull/298 closes this for me

**Comment by psobolewskiPhD** [comment]
Closed by https://github.com/napari/docs/pull/298
