### ISSUE TITLE
"back to top" position is set as a percent when it should probably be absolute

### ISSUE THREAD

**Issue by jni** [napari/napari-sphinx-theme#150]
On vertical windows it's really high off the bottom of the page and quite annoying. 😅 

<img width="710" alt="Screenshot 2024-02-06 at 12 43 00 pm" src="https://github.com/napari/napari-sphinx-theme/assets/492549/8b6da5fb-2c04-4365-90ba-2c0fbc81d967">

You can verify that it's proportional by making it a appear (by scrolling up) then resizing the window vertically.

I'd actually consider removing it altogether — we have Home keys and/or Cmd-Up for this... having it pop up when I'm just doing a little bit of referring back to the last paragraph is quite distracting rather than helpful...

**Comment by melissawm** [comment]
Hmm this is probably a pydata sphinx theme issue, as I never set that. Could you open it upstream?

**Comment by jni** [comment]
Hot damn — it was just fixed upstream: pydata/pydata-sphinx-theme#1497 pydata/pydata-sphinx-theme#1616

It's the gift that keeps on giving! 😃 

Looks like we can turn it off with `"back_to_top_button": False` in the theme config in `conf.py` starting with pydata-sphinx-theme v0.15.2. 😃
