### ISSUE TITLE
add "release events" to calendar selection

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-sphinx-theme#151]
## 📚 Documentation

As mentioned by @sofroniewn in https://github.com/napari/napari/discussions/4126, the napari community is now tracking release events in the community calendar.

It would be beneficial to let users filter these events in the community calendar: https://napari.org/community/meeting_schedule.html

**Comment by melissawm** [comment]
Do we still want to do this? I haven't seen release events on the calendar, so just want to be sure.

**Comment by psobolewskiPhD** [comment]
We hadn't had a release in like almost a  year so... 👀 
I think the idea of releases every month or something regular is still far off, so releases will be touch and go, but I do think we should aim to put RC release on the calendar--manually--when we know it's going to happen. 
So maybe we close this and play it by ear. If we get to a really regular cadence we put it on the calendar?
