### ISSUE TITLE
calendar should show event location 😅 

### ISSUE THREAD

**Issue by jni** [napari/napari-sphinx-theme#157]
This event has imagesc island attached to it as a location, but that turned out to be futile... 😭 

<img width="349" alt="Screenshot 2024-02-28 at 9 44 41 pm" src="https://github.com/napari/napari-sphinx-theme/assets/492549/ad651343-a789-43ff-aa1f-41200c292149">

**Comment by Czaki** [comment]
It is strictly mobile problem:
![obraz](https://github.com/napari/napari-sphinx-theme/assets/3826210/01f7de37-1009-43e8-9b97-9e8a4b216588)

**Comment by melissawm** [comment]
Hmm I'll need to check this. This is what I get on Firefox mobile:

![Screenshot_2024-02-29-10-07-17-559_org.mozilla.firefox.jpg](https://github.com/napari/napari-sphinx-theme/assets/3949932/7adb9ece-1055-40bf-a8c4-c6888dd9fcbb)

And Chrome mobile:

![Screenshot_2024-02-29-10-08-12-004_com.android.chrome.jpg](https://github.com/napari/napari-sphinx-theme/assets/3949932/79f0a683-1803-43fb-9c1a-1d8d5d199cbd)

Both on Android. Maybe there is some setting to turn on scrolling on smaller screens that I need to activate.

**Comment by psobolewskiPhD** [comment]
Looks fine in mobile safari:
![IMG_3F319E0B1DF0-1](https://github.com/napari/napari-sphinx-theme/assets/76622105/c9023143-919a-4218-9ceb-9b61cc9bfd95)

But I assume Juan just added it to the details of the event. There is no location field in any of the events mobile or not.

**Comment by melissawm** [comment]
I am looking into this and it seems like the best strategy would be to have some sort of structure for our meeting invites and use that for parsing. Otherwise I'm afraid this is going to get more complicated and hard to maintain. So if someone with access to the calendar (maybe @jni ) could go and make all of them look like e.g.:

```
Community meeting

Description ...

Agenda: <link>
Zoom link: <link>
Location: <link>
```

then I could make those into nicely formatted fields in the calendar.

**Comment by jni** [comment]
@melissawm I don't understand why arbitrary text fields are better than just grabbing the actual calendar event field for this? (Other than the fact that existing code already extracts the description.) The only thing is whether we *do* want to make sure that the description has all the info, in which case the other fields are redundant.

Anyway, I can update the descriptions. I'll just have "Agenda" and "Call link" so that we can switch providers at any time. 😊
