### ISSUE TITLE
Level 4 header larger than level 3 header

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari-sphinx-theme#158]
Level 4 header larger than level 3 header, "qtbot" is the level 4 header.

![image](https://github.com/napari/napari-sphinx-theme/assets/23182829/2dde3eb5-d686-4531-b142-bb19888bb65d)

This is from the rendered docs in https://github.com/napari/docs/pull/378/files, but I've also checked this is the case in the [asyn page](https://napari.org/dev/guides/rendering.html#future-work-compatibility-with-the-existing-image-class).

Possibly related to https://github.com/napari/napari-sphinx-theme/issues/141 ?

Maybe @melissawm knows more? :pray:

**Comment by melissawm** [comment]
Argh thanks for reporting, will fix ASAP.

**Comment by psobolewskiPhD** [comment]
This is fixed by #141 see from most recent CI action artifact.
<img width="685" alt="image" src="https://github.com/napari/napari-sphinx-theme/assets/76622105/f3966e61-4862-4e12-b15e-7f339c8abeb1">
The reason you see it in napari/dev docs is because the theme hasn't been released since the fix.

**Comment by melissawm** [comment]
Oh you are right - I thought I had left something out in that pr. In that case, maybe we should review any pending items here and if there's no bugs or feature requests should we just cut a new release?

**Comment by psobolewskiPhD** [comment]
The dark/light we have the solution for but bug is upstream.

**Comment by lucyleeow** [comment]
Ah thank you!!
