### ISSUE TITLE
Task: don't inject TOC into pages using javascript

### ISSUE THREAD

**Issue by tlambert03** [napari/napari-sphinx-theme#16]
**updated to reflect an actionable task**

In the new theme, it would be nice if inline content (like the toc at the top of the pages) was controllable with directives in markdown.  Using, for example, the `toctree` directive... but not editing the sphinx sources after generation.

-------------

**original post**

what is creating the red-outlined section here?

<img width="826" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/146563053-643a376b-507e-4e06-8b84-e2715c5c7b01.png">

**Comment by tlambert03** [comment]
Thanks @neuromusic... I'll edit this.  I think the concrete request here is to not add content (like a TOC) to the page using javascript.  I liked the general goal here of having uniformity, but sometimes these autogenerated TOCS aren't working or looking very good, and it leaves us without a way to edit it on a given page.  does that make sense?

**Comment by codemonkey800** [comment]
Did these issues get imported from `napari/napari.github.io`? We could probably close this since we're not using Node at the build step anymore

**Comment by codemonkey800** [comment]
Oh wait I see, it got repurposed to a separate issue. I think this depends on how the designs come out for the new theme with pydata

**Comment by tlambert03** [comment]
it's the same general issue, but yes, @neuromusic is moving all of the theme issues from `napari.github.io` to this repo.  Feel free to close this if you feel like the general point is clear and not going to be an issue in the next theme!

**Comment by neuromusic** [comment]
let's track this as a requirement in the tech spec, then close this issue. does that make sense @codemonkey800 ?

for the ToC, for example, we should be able to build it through the sphinx templating system: https://www.sphinx-doc.org/en/master/templating.html

**Comment by codemonkey800** [comment]
Closing this now that we've switched to pydata fork
