### ISSUE TITLE
When making the window more narrow, header bar doesn't expand

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari-sphinx-theme#162]
The items in the header go multiline, but the header area (blue bar) doesn't expand.

![image](https://github.com/napari/napari-sphinx-theme/assets/76622105/0137d71c-d995-443d-a3b1-8da04dbf0686)

Compare to parent pydata-sphinx-theme:
![image](https://github.com/napari/napari-sphinx-theme/assets/76622105/b5788125-a0e9-4dd4-aed2-285da13a743b)

The header bar widens to accommodate the double-line. I don't love the aesthetic, but it is objectively better than ours 🤣

**Comment by melissawm** [comment]
ooh interesting! Probably an upstream bug - would you mind opening an issue there?

**Comment by psobolewskiPhD** [comment]
I don't think it's upstream bug, I think I just wasn't clear:
Upstream wide look like this:
<img width="1287" alt="image" src="https://github.com/napari/napari-sphinx-theme/assets/76622105/8a915589-4e85-4502-8244-65872b16a51f">

And if you narrow it you can see the header space expands vertically--it between the shadow at the bottom and the purple banner:
![image](https://github.com/napari/napari-sphinx-theme/assets/76622105/3a2b5550-4286-40ef-9552-a0cc446791f6)

In our case, here is the wide view:
<img width="1409" alt="image" src="https://github.com/napari/napari-sphinx-theme/assets/76622105/18ec3e43-c42b-47d2-b902-2f1cc2d2834c">

Looks much like upstream.
But when I narrow it:
![image](https://github.com/napari/napari-sphinx-theme/assets/76622105/b8985afe-9382-4abf-8372-de8bcf27a811)

The blue header doesn't expand in the vertical direction (GitHub is auto sizing to fit width here, but I think you can see what's happening)

**Comment by psobolewskiPhD** [comment]
Apropos, upstream has a PR to improve the default look:
https://github.com/pydata/pydata-sphinx-theme/pull/1784
(but our issue is still something different, with the blue bar graphic not expanding)

**Comment by gabalafou** [comment]
Hi, I landed here from the cross-reference to the PyData Theme issue (1784). I think you can fix this issue by removing the `height: 64px` on the header. I'm not familiar enough with Napari docs to know if that's a viable solution, maybe you have an animation or some other reason you need to set the height explicitly, but if you don't need to set an explicit, fixed height, that should fix this issue, which is what I did in PR #163

**Comment by melissawm** [comment]
No we dont have any customization beyond the color, I will try that, thanks! ☺️
