### ISSUE TITLE
PyData Sphinx Theme 0.15.4 breaks navbar styling

### ISSUE THREAD

**Issue by melissawm** [napari/napari-sphinx-theme#166]
This is what it looks like with the new version of the PyData Sphinx Theme:
![Captura de imagem_20240709_183627](https://github.com/napari/napari-sphinx-theme/assets/3949932/5a05b4a2-8bd6-4bdc-b1ef-5730f3787087)

Navbar entries should have better spacing and be in bold font.

**Comment by jni** [comment]
and black not gray?

**Comment by jni** [comment]
Are our docs builds dependencies pinned or do we need to fix this ASAP? (0.5.0 is getting released very shortly!)

**Comment by melissawm** [comment]
Sorry I missed the question - yes they are pinned, see https://github.com/napari/docs/blob/0205abb3ac25a27fb0df5479138654716f3e20a8/.github/workflows/build_and_deploy.yml#L59
