### ISSUE TITLE
inconsistent behavior & styling for ToC items

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-sphinx-theme#17]
styling is inconsistent depending on whether we've linked to `index.html` or the path it lives in.

for example

https://napari.org/plugins/stable/ does NOT display the ToC at the top of the page
![image](https://user-images.githubusercontent.com/1245615/139110381-17be2df5-69cf-48ec-89c9-0c1b36105dfa.png)

whereas https://napari.org/plugins/stable/index.html does

![image](https://user-images.githubusercontent.com/1245615/139110477-5995b0b2-d863-4c82-bfaa-f55410d784da.png)

https://user-images.githubusercontent.com/1245615/139109932-af7ee487-ff82-4965-b0bc-45d1fc04dc51.mov

I believe that our preferred behavior here should be...

1. index.html links should redirect to the parent directory (e.g. https://napari.org/plugins/stable/index.html should redirect to https://napari.org/plugins/stable/)
2. the ToC should be displayed on page rendered at the parent directory
3. sidebar ToC links should link point to the parent, not the index.html file (however (1) would effectively fix this)

**Comment by codemonkey800** [comment]
@neuromusic is this something we can close now that we've switched to pydata fork?
