### ISSUE TITLE
Display of footer in latest version is not mobile responsive

### ISSUE THREAD

**Issue by willingc** [napari/napari-sphinx-theme#173]
The footer in the latest docs version is not mobile responsive. The stable version and older are mobile responsive.

**Comment by willingc** [comment]
@melissawm :wave: I'm assuming https://github.com/napari/napari/pull/7111 will fix this in the docs deployment. If so, feel free to close.

**Comment by psobolewskiPhD** [comment]
I hope so! Going to mark it ready to merge and hopefully we get this fixed.

**Comment by melissawm** [comment]
Yes it should 🙏thanks for flagging! ❤️

**Comment by melissawm** [comment]
This should be fixed now @willingc, would you mind confirming? Thanks again!

**Comment by psobolewskiPhD** [comment]
Looks good on my phone in Safari

**Comment by willingc** [comment]
Beautiful! Thanks @melissawm and team.
