### ISSUE TITLE
Name of Evented containers are not visible in the table of contents

### ISSUE THREAD

**Issue by Czaki** [napari/napari-sphinx-theme#175]
## 📚 Documentation

Name of Evented containers are not visible in the table of contents. To see the name there is a need to scroll to right after every link clik.

![Zrzut ekranu z 2022-04-26 15-45-06](https://user-images.githubusercontent.com/3826210/165314060-05f840db-6aad-4bdc-899b-a50e19abe891.png)

**Comment by psobolewskiPhD** [comment]
I mean it's note pretty, but it's definitely an improvement. So I think the issue could be closed.
In terms of improvements my idea would be that given the layout where there is the heading e.g. napari.utils.notifications
<img width="309" alt="image" src="https://github.com/user-attachments/assets/ddd4ebee-1b2c-4739-ae4b-3ca353a5fed8">
The items underneath it could drop that prefix, which would make the items shorter and probably eliminate the need for wrapping?
Doing so would match the look of the content:
<img width="700" alt="image" src="https://github.com/user-attachments/assets/119a5925-02ea-4215-a143-7499634dabdd">

**Comment by melissawm** [comment]
Like this (I just mocked it, will have to figure out how to implement):
![Captura de imagem_20240827_144328](https://github.com/user-attachments/assets/a08f7bb7-35a9-49c9-baab-8bd749cda695)

**Comment by psobolewskiPhD** [comment]
Yeah! Do you want to just make a new issue about the formatting detail? I think the important thing is fixed here. Making it pretty like that is 😍

**Comment by melissawm** [comment]
Superseded by #176.
