### ISSUE TITLE
On hover, the footer links should turn blue

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-sphinx-theme#19]
*from October 2021 pre-launch bug bash*

**Created by**: Lia

## Description 

This was not specified in the original design, sorry! But seeing it in real life seems like it'd be helfpul to have a bit of hover feedback, so the links should turn to light blue (#D2EFFF) on hover, as well as the icons. Let me know if it's not possible to style the SVGs' color with CSS, if I need to make versions of the SVGS in the light blue color!

## Info

**Bug source**: *unknown*

**Browser**: *unknown*

**PR**: *none*

**Comment by codemonkey800** [comment]
This is related to #75, so this issue will get closed when that issue is closed

**Comment by liaprins-czi** [comment]
@codemonkey800 Here's a link to the exported light blue icons:
https://drive.google.com/drive/folders/1cpXizCm48YTnGrAQMU6WZNGPCn_iQevc?usp=sharing

And here's where they are in Figma:
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=307%3A186
