### ISSUE TITLE
put napari logo as icon in browser tab

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari-sphinx-theme#2]
it would be nice if for napari.org the logo appeared as the icon in the browser tab

**Comment by psobolewskiPhD** [comment]
I believe this has been accomplished in the napari/docs repo: https://github.com/napari/docs/pull/4

**Comment by melissawm** [comment]
I see it in dev, but not in stable. I'm using Firefox on Linux (Manjaro).

**Comment by psobolewskiPhD** [comment]
Yeah, this is wierd. 0.4.17 should be out and the docs seem to reflect that, but the icon is just in dev and not stable still.

**Comment by psobolewskiPhD** [comment]
Interestingly, with 0.4.18 the icon is still not showing, but does show for dev. very odd.

**Comment by melissawm** [comment]
This works for me on 0.4.18, 0.4.19 and dev so I think it is fixed. @psobolewskiPhD can you check again?

**Comment by psobolewskiPhD** [comment]
For me it works with 0.4.19 and dev, but not 0.4.18 -- so basically new theme stuff, which is all the matters.
