### ISSUE TITLE
hamburger popup takes 1-3 seconds to load menu

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-sphinx-theme#23]
*from October 2021 pre-launch bug bash*

**Created by**: Justin

## Description 

on an older iPad (safari), when I click the hamburger, it takes 1-3 seconds for the menu to pop up

## Info

**Bug source**: *unknown*

**Browser**: safari

**PR**: *none*

**Comment by codemonkey800** [comment]
@neuromusic can you see if this is still an issue please?

**Comment by psobolewskiPhD** [comment]
I can't reproduce this on mobile and it's pretty old, so closing. If it is still an issue please re-open or make a new one.
