### ISSUE TITLE
Some API Reference method headers are not aligned inline appropriately

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-sphinx-theme#24]
*from October 2021 pre-launch bug bash*

**Created by**: Draga

## Description 

Most API Reference docs keep the method header and all parameters on the same line, but for some, the method parameters get bumped to a new line and are difficult to read.

https://napari.staging.imaging.cziscience.com/api/stable/index.html#modules

Note this is currently happening on the original website as well:
https://napari.org/api/stable/index.html

## Info

**Bug source**: Happens at all screen widths

**Browser**: Found it on Chrome, doesn't happen on Firefox

**PR**: *none*

## Attachments

Buggy:
![image](https://user-images.githubusercontent.com/1245615/137516626-53e1e0d3-63b5-4882-be0f-6d481a99ec79.png)

Normal: 
![image](https://user-images.githubusercontent.com/1245615/137516653-fecc432b-6690-4f0e-882f-c2ddff60c43d.png)

**Comment by codemonkey800** [comment]
@neuromusic  @DragaDoncila is this still an issue now that we're on the pydata fork?

**Comment by DragaDoncila** [comment]
Yep 🎉
