### ISSUE TITLE
migrate to Jupyter Book 0.11 (new TOC structure and migration tool)

### ISSUE THREAD

**Issue by jni** [napari/napari-sphinx-theme#30]
See the warning note near the top of this page:

https://jupyterbook.org/customize/toc.html

<img width="662" alt="Screen Shot 2021-06-07 at 10 22 36 am" src="https://user-images.githubusercontent.com/492549/120944901-49060180-c77a-11eb-87c7-7e0b208fb6ec.png">

**Comment by psobolewskiPhD** [comment]
This isn't relevant anymore as far as I can tell.
Closing.
