### ISSUE TITLE
implement primary elements of napari theme (typeface, type colors, interface colors, Interface elements)

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-sphinx-theme#31]
- [x] #41
- [x] #50
- [x] #51
- [x] #52
- [x] #53
- [x] #54
- [x] #60

**Comment by codemonkey800** [comment]
@liaprins-czi could you go through https://napari-sphinx-theme-test.vercel.app/demo/index.html and verify fixes for the above issues please? if you find anything that still needs fixing, could you post a comment in the Github issue relevant to it?

thank you!!

**Comment by codemonkey800** [comment]
I think headings is not fully complete yet since there's still some design work to do for the H4-H6 headings
