### ISSUE TITLE
Styling of large interface elements that need new design (left nav, sphinx-gallery, version switcher)

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-sphinx-theme#34]
- [x] #36
- [x] #48
- [x] #55
- [x] #69
- [x] #70 
- [x] #40

**Comment by liaprins-czi** [comment]
@neuromusic In the title of this issue it says "sphinx-gallery" but I didn't see that anywhere in the demo site (but I may have missed it)... do you know more about what this is or if we have an example of what it looks like? Thanks!

**Comment by neuromusic** [comment]
hmm... you're right. maybe we can get it built on the example site

**Comment by liaprins-czi** [comment]
@codemonkey800 Do you know about the sphinx-gallery? and if it is in the demo site somewhere (or even in the original [PyData demo site](https://github.com/napari/napari-sphinx-theme/issues/34)? I could not find it, but I might not know what to look for)

**Comment by codemonkey800** [comment]
I don't see any references to `sphinx-gallery` so it's probably not available, but we can always look into adding it later

**Comment by neuromusic** [comment]
@codemonkey800 the demo site gets built from https://github.com/napari/napari-sphinx-theme/tree/main/docs right? if so, I can get a sphinx-gallery example added today or tomorrow.

**Comment by codemonkey800** [comment]
yeah that's correct! that would be awesome 😄 send a PR and we can get it in
