### ISSUE TITLE
Line blocks

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#37]
- [x] Find out what constitutes a line block (is it just the part in the screenshot with the grey text + grey line to the left, or is it also / or the top part that says "This is a line block...") + what we need a design for
- [x] Design for "block quotes"

Here's a screenshot of the "Line Block" section of the Kitchen Sink:

<img width="596" alt="Screen Shot 2022-02-10 at 1 04 01 PM" src="https://user-images.githubusercontent.com/53277128/153680587-90c31fb5-bc71-4ecd-8260-9f4e51bb7688.png">

**Comment by liaprins-czi** [comment]
@codemonkey800 I am trying to figure out what counts as a "line block" in this PyData theme... in the screenshot above, right below "Line blocks" it says "This is a line block." and then "This is a second line block." a little further down. But both look just like normal text to me. But then further below, it has the grey chunk of text with the grey line next to it.

So what is a line block? Is it the grey text with the grey line next to it? Or the text above it (that looks like normal text to me)? Or are both different varieties of line block?

Just curious if you can tell from the code?

**Comment by codemonkey800** [comment]
a line block is a single line of text where each line is determined by the pipe character `|`, so users can write manually write really lines of text without the browser causing a line break.

```
| This is a line block.  It ends with a blank line.
|     Each new line begins with a vertical bar ("|").
|     Line breaks and initial indents are preserved.
```
<img width="348" alt="image" src="https://user-images.githubusercontent.com/2176050/154176872-d9054b11-c7dd-49bc-ad76-5f0160ba38de.png">

Here, each new line corresponds with a beginning pipe character, and empty spaces are preserved.

```
| Continuation lines are wrapped portions of long lines;
  they begin with a space in place of the vertical bar.
|     The left edge of a continuation line need not be aligned with
  the left edge of the text above it.
```
<img width="745" alt="image" src="https://user-images.githubusercontent.com/2176050/154177010-f7f2d76a-65f9-4cff-a085-054989d5b94d.png">

Finally, if you indent a line block by 4 spaces, it'll wrap it in a block quote:

```
    | A one, two, a one two three four
    |
    | Half a bee, philosophically,
    |     must, *ipso facto*, half not be.
    | But half the bee has got to be,
    |     *vis a vis* its entity.  D'you see?
    |
    | But can a bee be said to be
    |     or not to be an entire bee,
    |         when half the bee is not a bee,
    |             due to some ancient injury?
    |
    | Singing...
```

<img width="306" alt="image" src="https://user-images.githubusercontent.com/2176050/154177104-497a5880-1f76-475c-a7c1-191e2e788524.png">

**Comment by liaprins-czi** [comment]
Here's a link to the design for block quotes:
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=33%3A512

<img width="837" alt="Block quotes" src="https://user-images.githubusercontent.com/53277128/155402974-6163ad17-5346-490a-a5ca-17129e4f10ea.png">

**Comment by liaprins-czi** [comment]
Just needs to be updated so that there's 25px horizontal spacing between the black line on the left and the edge of the text. Now it has 17px spacing, and on both sides of the text (but should be 25px, and only on the left side of the text.)

**Comment by liaprins-czi** [comment]
The block quotes (with the black line to the left edge) look great to me now! But now I am realizing the "line blocks" (above the block quotes in the demo site) are the wrong size and color. They are 16px and #333333, but should be 17px and black. Other than that, this looks good to me!

**Comment by liaprins-czi** [comment]
Looks great!
