### ISSUE TITLE
"Next" + "Previous" links at bottom of each page

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#39]
- [x] Need to verify with others (@melissawm maybe?) the order that we want the docs to "flow" in... that is, what will each "next" button go to? Likely will need to follow the hierarchical structure of the docs, but in a flattened / linear way.
- [x] Need to design "Next" + "Previous" links at bottom of each page from scratch. 
- [x] Design for first (home) screen, where there is no "Previous" button, and vice versa for last screen

Here's what they look like without design:

<img width="796" alt="Screen Shot 2022-02-10 at 1 08 56 PM" src="https://user-images.githubusercontent.com/53277128/153678868-aab17698-6794-4863-8f00-400f8ad75ecc.png">

**Comment by liaprins-czi** [comment]
Update for reference: here is what it looks like in demo site when there is no "Previous" button (because you're on the "first" page) + when there is not "Next" button (because you're on the "last" page):
![Screen Shot 2022-02-23 at 11 44 30 AM](https://user-images.githubusercontent.com/53277128/155396255-97c0ad43-80f5-4f35-8bdb-e8b9b9192a45.png)
![Screen Shot 2022-02-23 at 11 44 52 AM](https://user-images.githubusercontent.com/53277128/155396257-1a7bd77b-3174-4867-9ffd-aee35094df74.png)

Bascially they just don't show any arrow, text, link / button. etc. I like this approach, and we will keep this. 

Designs for the text + icons in the "Previous" "Next" links coming soon!

**Comment by liaprins-czi** [comment]
Here's a link to the new design for the Next + Previous links:
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=32%3A275

![Next + Previous buttons](https://user-images.githubusercontent.com/53277128/155398311-e502080a-1470-4180-8280-4a029821fb75.png)

Here are links to the left and right chevrons / arrows:
[Left](https://www.figma.com/file/pDKU0CdSzpSWGaoXXQVJLz/v0-hub-final-designs?node-id=1724%3A96)
[Right](https://www.figma.com/file/pDKU0CdSzpSWGaoXXQVJLz/v0-hub-final-designs?node-id=1724%3A98)

It also shows the hover state. If user is on the "first" or "last" page, there will be no "Previous" or "Next" button, respectively.

**Comment by liaprins-czi** [comment]
Thanks for the updates to this one! There are just a few things that don't quite match the design yet:

- [ ] Shoudl have 75px of vertical spacing between bottom of text and top of footer
_What it looks like now:_
![Screen Shot 2022-03-02 at 10 18 46 AM](https://user-images.githubusercontent.com/53277128/156423981-979be65c-d3cb-405a-8e4b-db4f1ec3ca03.png)

- [ ] Shoudl have 25px of padding (light grey surrounding on hover)
_What it looks like now:_
![Screen Shot 2022-03-02 at 10 18 17 AM](https://user-images.githubusercontent.com/53277128/156424117-f4d5a4eb-4c16-4e28-8ca0-1716745a9d1b.png)

- [ ] Should have 25px of horizontal spacing between text and chevron
_What it looks like now:_
![Screen Shot 2022-03-02 at 10 17 45 AM](https://user-images.githubusercontent.com/53277128/156424218-bfd77324-edf7-45e0-b802-337d25e8742e.png)

- [ ] Ideally the left edges of the word "NEXT" and the text below it would be more flushly aligned (not a big deal if that can't be fixed)
_What it looks like now:_
![Screen Shot 2022-03-02 at 10 15 49 AM](https://user-images.githubusercontent.com/53277128/156424348-7dd48d6a-4fc3-4c9f-9fc0-566a2e245a52.png)

- [ ] In the designs, the edges fo the "NEXT" and "PREVIOUS" text (and the text below them) were left- and right-aligned (respectively) with the main body text above, and the chevrons were extended out into the margins. Is that possible or not? If it is not really feasible, no worries, just let me know, and we don't have to do that one in this first iteration!
_What it looks like now:_
![Screen Shot 2022-03-02 at 10 25 43 AM](https://user-images.githubusercontent.com/53277128/156424699-55b98ee4-8187-4a65-baf2-05b214cac855.png)
_Design:_
![Screen Shot 2022-03-02 at 10 26 30 AM](https://user-images.githubusercontent.com/53277128/156424803-fbaafe00-e76a-45d1-8a34-bbe1b7d69637.png)

**Comment by codemonkey800** [comment]
>  that possible or not? I

definitely, we can use [translateX()](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateX()) for this so that it doesn't mess with the box model 😄 

<img width="313" alt="image" src="https://user-images.githubusercontent.com/2176050/156845238-a8da1124-b04b-4568-bdc4-b4e5d2ab69cd.png">

**Comment by liaprins-czi** [comment]
These look so good! The only remaining thing I'm not seeing fixed yet is about the padding for the hover state: it should be 25px surrounding the whole chevron + text area, but it looks less than that to me still.

- [ ] Shoudl have 25px of padding (light grey surrounding on hover)
_What it looks like now:_
![Screen Shot 2022-03-02 at 10 18 17 AM](https://user-images.githubusercontent.com/53277128/156424117-f4d5a4eb-4c16-4e28-8ca0-1716745a9d1b.png)

_What it should be:_
![Screen Shot 2022-03-09 at 10 34 56 AM](https://user-images.githubusercontent.com/53277128/157508318-f523784d-fed4-4a40-a382-9666b7148c02.png)

**Comment by liaprins-czi** [comment]
Perfect! 🥇🏇
