### ISSUE TITLE
Improve information architecture, design and typography for API reference

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari-sphinx-theme#4]
Currently the API reference is difficult to browse for a number of reasons:
- As reported in napari/napari.github.io#251 the parameters are styled differently to the method names making them look inconsistent and possibly sometimes pushing them to the next line
- There is insufficient nesting within the main TOC on the left, making it hard to know what's available within each subsection
- Headers appear less bold than the code-styled words, making the separation between the different sections of the page difficultt to find e.g.

![image](https://user-images.githubusercontent.com/17995243/149241958-9310bd03-3f8b-4f93-b7c4-5a77a3190a3b.png)

- The methods, their parameters, and their descriptions are not visually grouped together in an expected way compared to other commonly used API docs. I think there are also insufficient visual cues separating the different kinds of text e.g. these are the dask docs

![image](https://user-images.githubusercontent.com/17995243/149242143-5b406753-d3ee-422d-892a-67a28aa62a3f.png)

vs. our own docs

![image](https://user-images.githubusercontent.com/17995243/149242234-93113b27-6ce1-4525-b5b9-da110861e352.png)

- The spacing between paragraphs and lines is too large to fit much of the information about a method or property on screen at once, making it difficult to get information at a glance

These are some of the specific issues I have noticed, but I encourage others to weigh in with specific feedback they have noticed.

In terms of good examples, I like dask, numpy and scikit-image:
![image](https://user-images.githubusercontent.com/17995243/149242448-d5b68da2-fbee-454e-9856-be74429c41b1.png)
![image](https://user-images.githubusercontent.com/17995243/149242564-9400ae62-89fc-41c1-a048-d9953ea00492.png)
![image](https://user-images.githubusercontent.com/17995243/149242637-7707a86a-92f0-4ae6-b8f2-b8573e52995c.png)

**Comment by codemonkey800** [comment]
@DragaDoncila now that we've switch to a fork of pydata sphinx theme, is this something we can close now?
