### ISSUE TITLE
Literal blocks

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#40]
- [x] Determine how these differ from code blocks; can they use the same design as code blocks, or do they need separate considerations?
- [x] If need their own design, create design for them

Current PyData implementation:

<img width="810" alt="Screen Shot 2022-02-10 at 1 03 28 PM" src="https://user-images.githubusercontent.com/53277128/153684243-dd5dbf6b-c7ce-447b-b60e-5c4c0bc6379c.png">

**Comment by liaprins-czi** [comment]
@codemonkey800  and / or @melissawm Do either of you have any experience with these "literal blocks" in documentation sites or can you tell if / how they differ from code blocks, by looking at the theme's code? 

I am just trying to understand how someone using our napari Sphinx theme would use these "literal blocks" so I can know how to best design them visually. My first hunch is to have them match the code block visual treatment, but would not want to confuse users, in case they are actually fundamentally different in some way?

**Comment by codemonkey800** [comment]
I'm actually not sure, it seems like they're regular code blocks

**Comment by codemonkey800** [comment]
it seems like they pretty much are code blocks: https://www.sphinx-doc.org/en/1.4.9/markup/code.html

> Examples of Python source code or interactive sessions are represented using standard reST literal blocks.

**Comment by melissawm** [comment]
I agree - they are just code blocks but don't need to have syntax highlight. I'd just use the same design as code blocks :+1:

**Comment by liaprins-czi** [comment]
Perfect, thanks so much for the info! So this one is now ready for implementing the original code block styles, whenever you're ready @codemonkey800 ; here's a link to the Figma with code block design (although it sounds like these may not apply to the "literal blocks"):
https://www.figma.com/file/pDKU0CdSzpSWGaoXXQVJLz/?node-id=1010%3A93

**Comment by liaprins-czi** [comment]
It'd be great if we can both these ["literal blocks"](https://napari.org/napari-sphinx-theme/demo/kitchen-sink/paragraph-markup.html#literal-blocks) and the [doctest](https://napari.org/napari-sphinx-theme/demo/kitchen-sink/paragraph-markup.html#doctest-blocks) and the [code blocks](https://napari.org/napari-sphinx-theme/demo/kitchen-sink/paragraph-markup.html#code-blocks) to match the [initial designs for code blocks](https://www.figma.com/file/pDKU0CdSzpSWGaoXXQVJLz/?node-id=1010%3A93). These are the main things I'm seeing that should be updated in order to match the designs:

- [ ] Text size 16px
- [ ] Line height 28px
- [ ] No shadow around the box
- [ ] No border around the box
- [ ] No rounded corners on the box
- [ ] 25px interior padding within the box, between box edge and text (EXCEPTION: if line numbers are included in the code box, those should be only 13px from edge, but actual code content should then still be 25px from right edge of line numbers)

[A couple of things that are new with the PyData theme](https://napari.org/napari-sphinx-theme/demo/kitchen-sink/paragraph-markup.html#emphasized-lines-with-line-numbers), that we didn't have a design for with our initial code block, are:
- highlighted lines
- numbered lines

So here's a design for those in Figma:
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=159%3A15

![Emphasized lines with line numbers](https://user-images.githubusercontent.com/53277128/156430215-8c3ec685-ab11-4534-bae6-86d394920b4b.png)

- the height of each highlight bar should be 28px
- it should span all the way across the whole code box
- code numbers should be right-aligned
- code numbers should be the same color grey as code comments (#6f6f6f)

**Comment by liaprins-czi** [comment]
Yeah! We should use the same breakpoints + font sizes as original (pre-Sphinx theme) napari.org. In the Figma there is the "Narrow" font size section, so those should be for the narrower mobile screens. So for the code blocks, inline code, and literal blocks it should be size 11px

**Comment by liaprins-czi** [comment]
There are still a few things from the checklist of fixes above that aren't applied yet (sorry if this one is still in-progress), but I will just re-iterate them here. Then it should be good!
- [ ] Text size 16px (for wider screens) / 11px (for narrower screens). Right now it looks like there are [two font sizes](https://napari.org/napari-sphinx-theme/demo/kitchen-sink/paragraph-markup.html#blocks) but not sure why one is applying in one place but not the other?
![Screen Shot 2022-03-09 at 10 57 23 AM](https://user-images.githubusercontent.com/53277128/157512943-0760e2cf-6981-448a-a5d4-1e4f7d04639e.png)

- [ ] Line height should be 28px for wider screens / 19px for mobile narrower screens
This should also fix the way highlighting looks.

_Current line highlighting:_
![Screen Shot 2022-03-09 at 11 05 33 AM](https://user-images.githubusercontent.com/53277128/157513451-648cd50b-ee0e-4eea-8d6c-a862609d5615.png)

 _Should be:_
![Screen Shot 2022-03-09 at 11 06 16 AM](https://user-images.githubusercontent.com/53277128/157513549-8012effc-5205-4e94-94db-53c58b6eaf8e.png)

- [ ] 25px interior padding within the box, between box edge and text (EXCEPTION: if line numbers are included in the code box, those should be only 13px from edge, but actual code content should then still be 25px from right edge of line numbers)
For this one, the line code boxes / literal blocks that have line numbers look good. But the others don't have any padding on the left:
![Screen Shot 2022-03-09 at 11 07 50 AM](https://user-images.githubusercontent.com/53277128/157513763-7ab539e1-4315-4fbc-9d70-ef6f21c8d43d.png)

- [ ] The code block numbers are too big (currently 16px), but should be 13px for wider screens / 9px for narrower screens

**Comment by codemonkey800** [comment]
@liaprins-czi thanks for catching that, removed the extra padding!

does this look correct now? 
https://napari.org/napari-sphinx-theme/demo/kitchen-sink/paragraph-markup.html#emphasized-lines-with-line-numbers

<img width="755" alt="image" src="https://user-images.githubusercontent.com/2176050/157934698-429d15d0-5a56-4fb9-93fc-b34b10f6c408.png">

**Comment by liaprins-czi** [comment]
This looks great! 🪁
