### ISSUE TITLE
Version switcher

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#43]
- [ ] Design this to better match our look and feel, drawing heavily from the existing design for version selection, if possible.
- [ ] Also design the resulting dropdown of selection options, if we have control over the look and feel 

But wait to implement this until next version of PyData theme comes out, as it will have a better way to update it thematically, per @melissawm [on Slack](https://czi-sci.slack.com/archives/C02450UPFR9/p1644529387320439?thread_ts=1644528430.952599&cid=C02450UPFR9):
> Wow - that looks beautiful! :sparkling_heart: For the version switcher, I was asking around and it looks like at this point the best plan is to wait for the next release of the pydata-sphinx-theme if we want to use their machinery. It looks like it is very experimental right now and has a few limitations which will be solved later - among those is the possibility of styling it in an easier way to have it match the rest of the color scheme for the site.  I’ll also add this comment to my open PR and remove the version switcher from the nav-bar for now.

What version switcher looks like in our PyData demo site:

<img width="246" alt="Screen Shot 2022-02-10 at 1 00 28 PM" src="https://user-images.githubusercontent.com/53277128/153686489-39231847-94cd-452c-aab7-d01b530e3d62.png">

What version switcher looks like in original designs:
<img width="245" alt="Screen Shot 2022-02-11 at 4 00 04 PM" src="https://user-images.githubusercontent.com/53277128/153686526-fffc94ce-16fc-410e-924c-bf9db3aaf835.png">

**Comment by liaprins-czi** [comment]
@codemonkey800 Do you know how much control we'd have over this element? And how much control (visual treatment-wise) over the resulting dropdown that would appear upon clicking it? We can also wait for the next version fo PyData theme to look into this more, as Melissa had said they'd be doing work on the version switcher to make it more customizable...

**Comment by codemonkey800** [comment]
Since it's a fork, we have full control over this element. However, I'd be fine waiting for the next version so that we don't have to deal with the merge conflicts later

**Comment by liaprins-czi** [comment]
Here's a link to the new version switcher design in Figma:
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=44%3A5
![Version switcher _ Open](https://user-images.githubusercontent.com/53277128/155431521-a03d80fc-1614-4e68-a807-ec9b043064d3.png)
![Version switcher _ Closed](https://user-images.githubusercontent.com/53277128/155431527-f7a09828-7348-404e-9eae-04a4b032ff14.png)

The dropdown list is very similar to the dropdown list in PyData by default, but I changed the font to our font, Barlow (and at same size as text within Admonitiions), and the grey for the borders I changed to #c4c4c4. Also, the dropdown should be left-aligned with the "version X.X.X" dropdown label, and the width of the dropdown should be as narrow as it can to fit all text across, including internal padding.

**Comment by liaprins-czi** [comment]
So cool that you added fake "versions" to be able to see the dropdown styles, thanks! Here are a few updates to make it better match the designs:
- [ ] Font weight of "version X.X.X" that functions as the clickable label to open the dropdown should be Barlow Medium (I can't tell what CSS font-weight number this is currently, but I know it is a little to light weight)
- [ ] Chevron should switch to haveing its point upwards when the dropdown is open
- [ ] Chevron should be aligned to base of "version X.X.X" text, whether it is open or closed (now it is shifted downwards a little too low)
- [ ] Needs a little more horizontal spacing between the end of the "version X.X.X" text and the left edge fo the chevron; should be 10px spacing
- [ ] Selectable version numbers in the dropdown should not have underlines
- [ ] Selectable version numbers in the dropdown should be size 14px (now 16px)
- [ ] Selectable version numbers in the dropdown should be black (now they are a different grey color we don't have as a color for napari.org or hub, probably a PyData default)

**Comment by liaprins-czi** [comment]
This looks great! Nice work! 🤩
