### ISSUE TITLE
"Edit this page"

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#46]
- [x] Verify if this will always be shown to every visitor, or only some / if currently logged into something, etc?
- [x] Find out if we can move this from its current location on page
- [x] Design, considering:
- Location on page
- Type size, weight, color, etc
- Icon: do we need it? If so, redesign

Here's what we get for free from PyData:

<img width="192" alt="Screen Shot 2022-02-10 at 1 00 15 PM" src="https://user-images.githubusercontent.com/53277128/153687198-11279802-cbde-4237-adcb-e8542c6c534e.png">

**Comment by liaprins-czi** [comment]
@codemonkey800 Do you know if we'd be able to move the "Edit this page" link to a different spot on the page (but would be consistent across all our pages)? Not sure if we should or not yet, just want to be aware fo the options before suggesting something that's not feasible, or alternatively assuming we can't do something when maybe we could...

**Comment by codemonkey800** [comment]
of course, we have the template as part of the fork, so we can move it wherever and style it however we want

**Comment by liaprins-czi** [comment]
Let's keep this "Edit this page" link where it is, below (25px below) the right-side nav. I have updated the font size and font weight (Medium), and also made a new pencil icon.
[Link to the Figma](https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=127%3A365)
[Link to new pencil icon](https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=126%3A252)

![Edit this page](https://user-images.githubusercontent.com/53277128/155815766-d1ac9100-3c1a-4838-a174-8915b9babdf0.png)

**Comment by liaprins-czi** [comment]
This looks good, except for one tiny thing: the text is color #333333, but it should be black:
<img width="315" alt="Screen Shot 2022-02-28 at 4 14 22 PM" src="https://user-images.githubusercontent.com/53277128/156080442-6ec30bfa-01b6-4962-81fb-31d0838241e8.png">

**Comment by liaprins-czi** [comment]
Awesome work!
