### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#47]
- [x] Explore whether this could / should still live at top of page or, if it's definitely better above left sidebar
- [x] If it could work at top of screen, get alignment with community, steering council et al on whether it should go there or above left nav
- [x] Design final; it should match design aspects of current search bar, including:
- More minimal "bar" (just a line below, not a box)
- Use our magnifier icon
- If possible, use our "x" interaction like on hub, once there is a searched for term in the bar
- Line + icons black, not grey
- [x] Align on hint text content

Here's what it looks like with our PyData demo:

<img width="348" alt="Screen Shot 2022-02-10 at 12 59 59 PM" src="https://user-images.githubusercontent.com/53277128/153687564-7b8d5908-b576-4e77-928a-344abd36259a.png">

Here's what the original search bar design looks like:

<img width="917" alt="Screen Shot 2022-02-11 at 4 19 45 PM" src="https://user-images.githubusercontent.com/53277128/153687604-284b19e4-ee04-44f9-bdcf-56418db41d9c.png">

**Comment by liaprins-czi** [comment]
Here's a link to the Figma with the final search bar design:
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=21%3A140

Search bar should stay in the location it is in the default PyData theme, but update visuals to match the current [napari.org](https://www.figma.com/exit?url=http%3A%2F%2Fnapari.org) search bar

![Search bar](https://user-images.githubusercontent.com/53277128/155242684-9bdc8b55-4c69-4dd8-99cc-d4273b891a98.png)

**Comment by liaprins-czi** [comment]
Search bar looks really good! There are just a couple of things that I am wondering if we can update? these may be difficult to change, so if that's the case, let me know and we don't have to worry about them for this iteration!
- [ ] When I click into search bar, a blue rounded rectangle appears. The cursor does not appear, which is disorienting, and makes it seem that the focus is actually _not_ in the search bar and that I can't start typing yet. Ideally, the cursor would show up, but not the blue box. If we need the blue box or something similar for a11y purposes for example, let me know! I can design something more specifically for that purpose!
![Screen Shot 2022-03-02 at 1 33 17 PM](https://user-images.githubusercontent.com/53277128/156453817-76a668dc-e592-4232-8a3d-b23efd2aba8d.png)

- [ ] When I've typed in something, a strange-looking "x" appears next to the search icon (magnifier). Ideally, we'd have the same behavior we have with the hub search bar: an "x" icon doesn't appear until the search results are displayed (in this case, on the search page), and the "x" would be in place of the magnifier. If the "x" is clicked, it clears the input and is replaced by the magnifier. If not possible to follow this behavior, is it possible to [use our own "x" icon design](https://www.figma.com/file/NmdYwtpKfMzLnNLYYWrbTw/napari.org-final-designs?node-id=298%3A27) instead of the (presumed) browser default?
![Screen Shot 2022-03-02 at 1 33 29 PM](https://user-images.githubusercontent.com/53277128/156454600-ed89713d-14da-460d-84a5-827f524039a5.png)

**Comment by liaprins-czi** [comment]
Soudns good! I just created #82

**Comment by codemonkey800** [comment]
@liaprins-czi  awesome, should we close this one then?

**Comment by liaprins-czi** [comment]
Yes, good call, closing it now!
