### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#55]
Consider whether we want our design to hide the top-level menu as soon as the screen is too narrow to fit it across, or is there a better way. Align with community + steering council.

Also, for the screen sizes where we do need a hamburger menu, it should [use the original icon](https://www.figma.com/file/NmdYwtpKfMzLnNLYYWrbTw/napari.org-final-designs?node-id=298%3A25).

**Comment by liaprins-czi** [comment]
Okay this one is ready to go; we will be keeping the default PyData theme behavior, wherein the top menu collapses into a hamburger menu once there is no more space for the top menu items to fit across. The only updates are:
- The social icons are not staying in the top, but in the footer instead (#38 )
- Use the [original napari.org hamburger icon](https://www.figma.com/file/NmdYwtpKfMzLnNLYYWrbTw/napari.org-final-designs?node-id=298%3A25) instead of default PyData icon
- There will be a new style for the top bar nav items, but they are covered by #45

**Comment by liaprins-czi** [comment]
There are a few things to update, but overall this is looking good!
- [ ] "version X.X.X" should be left-aligned with the other items in the list
- [ ] Larger spacing needed around the bottom and left edge: should be 50px if screen is narrower than 495px, or 25px if 495px or less
- [ ] Should not have a shadow below the top menu bar, or when it is opened as hamburger menu either 
- [ ] Ideally hamburger icon should change to an "x" when open (if this is not easible feasible for now, let me know and we don't have to worry about it for now)

**Comment by liaprins-czi** [comment]
Looks great to me! Thanks!

**Comment by codemonkey800** [comment]
lol @liaprins-czi should we close this one?

**Comment by codemonkey800** [comment]
i'm guessing so but please reopen if you have other feedback please 😄

**Comment by liaprins-czi** [comment]
Oops sorry I meant to close!
