### ISSUE TITLE
Monospace font on site is too large

### ISSUE THREAD

**Issue by jni** [napari/napari-sphinx-theme#6]
The size of the inline monospace font on the site seems too large. Not sure if it's just an optical illusion but the size in code blocks looks ok in comparison.

My typography chops are very amateurish but I think we probably want to match the x-height of the body (sans) font and the monospace font we use?

![napari-site-monospace](https://user-images.githubusercontent.com/492549/145706036-469091d0-3e14-4911-a575-5d390f90e829.png)

**Comment by codemonkey800** [comment]
@jni how does this look on the new sphinx theme? is this something we can close?

**Comment by ctrueden** [comment]
<img width="1579" alt="napari-evenly-spaced-lines" src="https://user-images.githubusercontent.com/556626/160901704-9ff14c93-9020-4409-b832-b425f333bc52.png">

@codemonkey800 Looks pretty even to me now! 🤓

**Comment by codemonkey800** [comment]
@ctrueden oh wow you did this in napari?! this is incredibly meta 😆 thank you for this!

**Comment by psobolewskiPhD** [comment]
This was fixed previously.
