### ISSUE TITLE
Figures + captions

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#61]
- [x] Design specifications for figures (alignment)
- [x] Design specifications for captions
- Alignment
- Type size
- Weight
- Color
- Line height

Here's what we get for free from PyData:
<img width="793" alt="Screen Shot 2022-02-11 at 4 44 00 PM" src="https://user-images.githubusercontent.com/53277128/153967846-a95974fb-f4de-4bb3-a73d-1c8a67636a62.png">

Also consider how they'll work with "Hlists"...
<img width="801" alt="Screen Shot 2022-02-11 at 4 48 43 PM" src="https://user-images.githubusercontent.com/53277128/153970746-2738ac2f-b10e-4123-8b53-a571ae9fc643.png">

**Comment by liaprins-czi** [comment]
Here's the link to the design for figures and for captions in Figma (scroll to the right to see it as a large image):
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=124%3A371

<img width="838" alt="Figure + caption | small" src="https://user-images.githubusercontent.com/53277128/155810755-3f9ae5f3-c5fe-4127-8fd9-e7f942decbe9.png">

<img width="834" alt="Figure + caption | large" src="https://user-images.githubusercontent.com/53277128/155810740-17c0cdde-df60-4f14-85b3-533f819f0ac7.png">

The main differences between the new design and the PyData default:
- now both the image and the caption default to be left-aligned to the main body text (instead of centered)
- the caption text now has the same treatment as the main text within Admonitions
- the maximum width for an image should be the with of the body text

**Comment by liaprins-czi** [comment]
There are a couple of things to update for this one, and then it should be good to go!
- [ ] Captions should be in italics
- [ ] It's correct to now have the captions left-aligned by default, but there's one place where thy're supposed to be able to be centered, but they aren't
<img width="325" alt="Screen Shot 2022-03-14 at 4 24 57 PM" src="https://user-images.githubusercontent.com/53277128/158277427-f2b2808c-fb1d-40af-969d-04b99cbf2bb5.png">

- [ ] Caption should be completely left-aligned with image, now it has a slight padding on left side
<img width="143" alt="Screen Shot 2022-03-14 at 4 24 23 PM" src="https://user-images.githubusercontent.com/53277128/158277530-9b52d859-441d-483c-9ccc-55353f341539.png">

- [ ] Similarly, when comparing the "[image](https://napari.org/napari-sphinx-theme/demo/kitchen-sink/paragraph-markup.html?highlight=admonition#images)" to the "[figure](https://napari.org/napari-sphinx-theme/demo/kitchen-sink/paragraph-markup.html?highlight=admonition#figures)", the figure is slightly indented with padding, but should not be
<img width="325" alt="Screen Shot 2022-03-14 at 4 24 57 PM" src="https://user-images.githubusercontent.com/53277128/158277725-baf18473-f31d-4203-9577-3c92e09791e0.png">

**Comment by liaprins-czi** [comment]
The fix looks great to me!

One last thing I noticed is that the images in the [demo site example](https://napari.org/napari-sphinx-theme/demo/kitchen-sink/paragraph-markup.html?highlight=figures#images-figures) look low resolution. [In the original PyData theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/demo/kitchen-sink/paragraph-markup.html?highlight=figures#images-figures), the images are not forced to be the same width as the frame. 

I think that ideally, we'd allow images to be smaller than the width of the frame, both to preserve their resolution, but also to allow smaller sized images (sometimes people might have a screenshot of just a small part of their screen as part of their documentation and it would not make sense for it to be humungous-looking). But if an image would be wider than the main content frame width, then we constrain it to max-width being the main content frame width (also like in the [Figma designs](https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=124%3A371))

**Comment by codemonkey800** [comment]
@liaprins-czi That makes sense to me! Thankfully, CSS has `max-width: content` that will do exactly what you want 😆 

I've deployed a fix, please verify when you get a chance!

**Comment by liaprins-czi** [comment]
Looks great! 🐝🦋🐌
