### ISSUE TITLE
Admonitions

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#62]
- [x] Find out if we need / should have icon per admonition type
- [x] Verify current admonition design supports all permutations available (see screenshot) + that all text varieties available in an admonition have designs defined

See also #10 

<img width="802" alt="Screen Shot 2022-02-11 at 4 44 37 PM" src="https://user-images.githubusercontent.com/53277128/153968117-6220997d-24df-4e53-94c4-ad07b16c47cf.png">

<img width="786" alt="Screen Shot 2022-02-11 at 4 44 47 PM" src="https://user-images.githubusercontent.com/53277128/153968133-878e8f5a-f35c-40f4-ad84-fe7875e79c29.png">

<img width="793" alt="Screen Shot 2022-02-11 at 4 49 43 PM" src="https://user-images.githubusercontent.com/53277128/153971564-52b29e31-6a19-4160-845b-ebc2ef0a9959.png">

**Comment by liaprins-czi** [comment]
Since we don't need to use icons for the Admonitions, let's remove them. Some are currently redundant in the PyData and base Spinx themes, which is very confusing. There are honestly way too many admonition types / levels for each to have a meaningful icon. The color + name of the admonition alone (or user-titled name, if customizing the title) will do a much better (less confusing) of communicating its meaning / importance.

So that means we can use the same exact design that we have in the current napari.org. Here's a link to all the admonition level designs (al the same except for their color + title) in Figma:
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=61%3A574

![Admonition _ Danger](https://user-images.githubusercontent.com/53277128/155595583-800d8c97-16c9-44c9-91e6-ac3ff575f565.png)
![Admonition _ Warning](https://user-images.githubusercontent.com/53277128/155595590-7f22714a-a1ed-49f1-979e-92ddefc9231a.png)
![Admonition _ Caution](https://user-images.githubusercontent.com/53277128/155595592-49a9356a-fea0-41a8-a628-102a2595874c.png)
![Admonition _ Error](https://user-images.githubusercontent.com/53277128/155595594-b6eb38dc-1c43-435d-b421-9bb5320e8450.png)
![Admonition _ Important](https://user-images.githubusercontent.com/53277128/155595600-6babe71f-2271-4e2b-a82e-1e3ad39d8ff2.png)
![Admonition _ Attention](https://user-images.githubusercontent.com/53277128/155595603-5cb2713d-6b42-45f8-a38e-0759a22743a7.png)
![Admonition _ Admonition](https://user-images.githubusercontent.com/53277128/155595610-c924eded-397b-4194-b3c1-270a3349ebd3.png)
![Admonition _ Note](https://user-images.githubusercontent.com/53277128/155595614-8f0e7f73-0760-4410-bed7-d374d88b2398.png)
![Admonition _ Hint](https://user-images.githubusercontent.com/53277128/155595619-2ddaff9c-c87e-4e15-9c71-d6e74a4b0c96.png)
![Admonition _ Tip](https://user-images.githubusercontent.com/53277128/155595623-453adbcd-128c-4233-b221-9dc97b64e77f.png)

**Comment by liaprins-czi** [comment]
The colors are matched up to the corresponding admonition, but the rest of the admonition styles aren't matching the design yet:
- [ ] Should not have a shadow around the box
- [ ] No rounded corners
- [ ] Every box should have a 1px outline in the same color as the admonition heading
- [ ] Font size should be 14px (for wide screens) / 9 px for narrow screens (<= 495px wide)
- [ ] Font weight should be Barlow Medium (500)

**Comment by liaprins-czi** [comment]
This one is close, but needs a couple more updates:
- [ ] Every box should have a 1px outline in the same color as the admonition heading (now they have no outline)
- [ ] Font weight for the main copy inside the boxes should be Barlow Medium (500), now it is Regular (400)
- [ ] Font weight for the header of each admonition should be Barlow Bold (700), now it is Medium (500)

Then it will be ready to go!

**Comment by codemonkey800** [comment]
ahhh, not sure how i missed that. definitely looks better with the border 

<img width="752" alt="image" src="https://user-images.githubusercontent.com/2176050/158492568-9d7f6f3c-e936-4fa6-ab83-e8d1c630cca1.png">

**Comment by codemonkey800** [comment]
@liaprins-czi a couple of other things I noticed I forgot:

- [ ] I used the wrong color for attention admonitions. I used `#80ffe0` which is for Note admonitions, when it should be `#d8f97d`
<img width="757" alt="image" src="https://user-images.githubusercontent.com/2176050/158850650-e7fc784e-818b-4468-a9dc-6e97d66d7338.png">

- [ ]  Default admonitions do not have the outline
<img width="760" alt="image" src="https://user-images.githubusercontent.com/2176050/158850759-c6c3a61a-5936-4202-8ae9-274cebcd51e9.png">

I'll have fixes for all of the above soon 😄

**Comment by codemonkey800** [comment]
ooooooh also @liaprins-czi  In GitHub, it looks like if you surround the color in backticks, it'll render the color next to the hex string 🤩 

```
`#80ffe0`
```

becomes

`#80ffe0`

**Comment by liaprins-czi** [comment]
Oooh! Awesome fing @codemonkey800 ! That's the same as in Slack, too!

**Comment by liaprins-czi** [comment]
These look good to me! Great work! 🥸🦄
