### ISSUE TITLE
Topics + sidebars

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#64]
Design for "topics"; consider:
- background color
- text size, weight, color
- borders
- make sure they work with sidebars

Design sidebars, to go with topics

<img width="788" alt="Screen Shot 2022-02-11 at 4 45 10 PM" src="https://user-images.githubusercontent.com/53277128/153968548-b4c501a9-f0ce-46e1-b2e4-59f33214b10a.png">

**Comment by liaprins-czi** [comment]
More info on Sidebars:
https://docutils.sourceforge.io/docs/ref/rst/directives.html#topic
> A topic is like a block quote with a title, or a self-contained section with no subsections. Use the "topic" directive to indicate a self-contained idea that is separate from the flow of the document. Topics may occur anywhere a section or transition may occur. Body elements and topics may not contain nested topics.
> The directive's sole argument is interpreted as the topic title; the next line must be blank. All subsequent lines make up the topic body, interpreted as body elements.

**Comment by liaprins-czi** [comment]
Here's a link to the new design for topics in Figma (scroll to left to see designs for topics when there are also "sidebars" within them, which is possible according to the demo site):
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=47%3A553

Plain old topic:
![Topic](https://user-images.githubusercontent.com/53277128/155437150-bd7d11cf-fcc1-4e98-a626-908545caa33d.png)

Plain old sidebar:
![Sidebar](https://user-images.githubusercontent.com/53277128/155437215-f05908c5-f5ec-449f-8eb5-b8f758adea81.png)

Topics with sidebars inside!
![Topics with long sidebar inside](https://user-images.githubusercontent.com/53277128/155437243-bcee50a0-7eda-46da-9f65-d43556f996c3.png)
![Topics with short sidebar inside](https://user-images.githubusercontent.com/53277128/155437247-466ce987-3f8d-4254-9c73-7447ecf632ff.png)

**Comment by liaprins-czi** [comment]
Also, here's a screenshot showing how the "titles" of both should be base aligned, and their text too:
<img width="881" alt="Topics with sidebar inside redlines" src="https://user-images.githubusercontent.com/53277128/155437528-58832d0f-e263-4ef0-af28-a8cc3cdd75e7.png">

Three column grid used to define width of sidebar:
<img width="855" alt="Topics with sidebar inside grid" src="https://user-images.githubusercontent.com/53277128/155437723-79d40d07-f0fe-4639-a86e-a3481c514e5f.png">

Note that the main text within both sidebars and topics is the same visual treatment (size, weight, lineheight, etc) as for Admonitions. The title for topics is the same visual treatment as H3; the title for sidebars is the same visual treatment as for H4.

**Comment by liaprins-czi** [comment]
Lastly, here are the mobile versions (also in the Figma if you scroll to the right to see them all):
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=47%3A754

![Sidebar _ Mobile](https://user-images.githubusercontent.com/53277128/155438460-95a105cc-ec62-4f49-9eab-888a1a692de7.png)
![Topic with sidebar inside _ Mobile](https://user-images.githubusercontent.com/53277128/155438464-ed5d7ee9-efe7-416f-80d0-249cbd6cba63.png)
![Topic _ Mobile](https://user-images.githubusercontent.com/53277128/155438465-cf776feb-53a5-420e-be27-2166cb4bd6cc.png)

**Comment by codemonkey800** [comment]
The HTML structure places the sidebar above the topic. It's not immediately obvious how to change the order, so I think the mobile sidebar + topic will need to come in the next release

**Comment by liaprins-czi** [comment]
> The HTML structure places the sidebar above the topic. It's not immediately obvious how to change the order, so I think the mobile sidebar + topic will need to come in the next release

Ah, okay, no worries! Thanks for the info!

**Comment by liaprins-czi** [comment]
Looking good! Here are few things to update to help Topics and Sidebars better match the designs:
- [ ] Left padding of sidebar (between eh black line and the text) should be 25px
- [ ] For both, the font weight of the main copy (not heading) should be Medium (500)
- [ ] The font size for both should be 14px (for wide screens) / 9 px for narrow screens (<= 495px wide)
- [ ] Looks like the Sidebar is not properly interacting with code block: the text for one of the examples says "A code example with a sidebar on the right" but the sidebar is actually above it
![Screen Shot 2022-03-02 at 2 51 53 PM](https://user-images.githubusercontent.com/53277128/156465195-66645544-a06c-42b9-994a-52aeadc41c6e.png)

- [ ] Topic title is too small: should be same size + weight as H3 (Sidebar title is correct though! It is supposed to be same size as H4, which it is)
- [ ] Sidebar main text size is too large; should be 14px (for wide screens) / 9 px for narrow screens (<= 495px wide)

**Comment by liaprins-czi** [comment]
All the things I listed earlier are fixed (well not the code sample with sidebar, but [that's how it is in PyData](https://pydata-sphinx-theme.readthedocs.io/en/latest/demo/kitchen-sink/paragraph-markup.html#code-with-sidebar) anyway, so I guess it's supposed to be that way!)! 

But I found a couple new things:

- [ ] Padding around edge of topic (between edge and text inside it) should be 25px, but on the left edge it looks narrower
![Screen Shot 2022-03-09 at 9 37 12 AM](https://user-images.githubusercontent.com/53277128/157499707-0bfc20a2-4653-453c-a2ff-fa3df0d0df23.png)

- [ ] When Sidebar is inside of topic, the sidebar should reach all the way to the bottom of the topic (unless the sidebar text is shorter than the topic text). Currently, when sidebar text is longer than topic text, though, there is still a little bit of the topic box showing below the bottom edge of the the sidebar:
![Screen Shot 2022-03-09 at 9 37 28 AM](https://user-images.githubusercontent.com/53277128/157500085-402ef9f8-6461-4369-8ea5-4c2e3752a276.png)

**Comment by codemonkey800** [comment]
> well not the code sample with sidebar, but [that's how it is in PyData](https://pydata-sphinx-theme.readthedocs.io/en/latest/demo/kitchen-sink/paragraph-markup.html#code-with-sidebar) anyway, so I guess it's supposed to be that way!)

ooh I forgot to mention that, yeah this looks like expected behavior

**Comment by liaprins-czi** [comment]
Looks great to me! 💙
