### ISSUE TITLE
Numbered + bulleted lists

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#66]
- [x] Design numbered lists, considering text treatment of numbers (type size, weight, color, etc)
- [x] Design bulleted lists, consider bullet disc shapes, whether numbers can be right-aligned!
- [x] For both, consider
- indentation depths
- spacing between bullet and following text

<img width="405" alt="Screen Shot 2022-02-11 at 4 48 52 PM" src="https://user-images.githubusercontent.com/53277128/153970912-ad15ef40-cd4c-4149-8e88-a640c50cb205.png">

<img width="379" alt="Screen Shot 2022-02-11 at 4 46 57 PM" src="https://user-images.githubusercontent.com/53277128/153969394-14cb0b08-b94b-4799-adac-d14fd1c82281.png">

<img width="261" alt="Screen Shot 2022-02-11 at 4 48 23 PM" src="https://user-images.githubusercontent.com/53277128/153969411-42b4adab-f9b9-4e25-99bb-be9a5d2ae6c4.png">

**Comment by liaprins-czi** [comment]
Here are links to the [bulleted list](https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=36%3A144) design and the [numbered list](https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=36%3A111) design.

![Bulleted list](https://user-images.githubusercontent.com/53277128/155415315-fc151fe4-4c41-4b52-a230-4b56418f0a57.png)

![Numbered list](https://user-images.githubusercontent.com/53277128/155416588-749b3055-ad67-46c4-a9ad-d2e504ae0961.png)


The red dashed lines show how the indented bullets should align to the _content_ of the bullet above.
For the numbered bullets, they should be right-aligned with other numbered bullets of the same indentation level, shown with blue dashed lines (I think this is how it is by default in HTML?). Let me know if there's any questions about this, or if it's not feasible how I have it shown in the designs!

**Comment by liaprins-czi** [comment]
These look so good! The only thing that is a tiny bit off is the alignment of the disc bullets: they should be directly below the left-edge of the text above, but right now they are bumped over a little too far to the left:

_What it looks like now:_
![Screen Shot 2022-03-02 at 3 15 40 PM](https://user-images.githubusercontent.com/53277128/156466103-4d77915b-881d-4177-a26b-4c1ae8bb3a8a.png)

_What it should look like:_
![Screen Shot 2022-03-02 at 3 20 22 PM](https://user-images.githubusercontent.com/53277128/156466197-2d88e146-2026-4fd0-a446-7fd36760136b.png)

**Comment by codemonkey800** [comment]
hmm, I'll use a padding unit of 20px, but if you can come up with one could you let me know? CSS is cascading, so the padding is used on top of each other.

In this case, the first list item has padding of 20px, the 2nd nested list item has padding of 40px, and so on.

**Comment by liaprins-czi** [comment]
@codemonkey800 I just checked the spacing I used in the Figma mockup, and it's almost exactly 20px! So 20px should work well! Thanks!

**Comment by liaprins-czi** [comment]
Looks lovely to me! 🍡🍢🐛
