### ISSUE TITLE
Field lists

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#68]
Design field lists, considering for both the label and the value:
- type size
- type weight
- line height
- color
- alignment

Here's the default we get with PyData:
<img width="799" alt="Screen Shot 2022-02-11 at 4 47 35 PM" src="https://user-images.githubusercontent.com/53277128/153970495-8b93efcd-d9bf-4029-8a8e-7c6a8dad9b68.png">

**Comment by liaprins-czi** [comment]
Here's the design for field lists in Figma:
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=33%3A538

<img width="1415" alt="Field lists" src="https://user-images.githubusercontent.com/53277128/155405211-3ac2f4a0-bc16-4895-a621-f8d0b9f7201d.png">

A couple of things different in this new design from the PyData default:
- now the labels are right-aligned (this makes it easier for the eye to track from the label to its value, as they are always a consistent distance apart (10px))
- the labels are Barlow Semibold
- All text in the field lists is the same size as text inside of admonitions
- line-height within a single list item (e.g. if it runs to the next line) is 1.5, but the spacing between list items vertically is ~18px

**Comment by liaprins-czi** [comment]
There are a couple of things to update for this one, then it will be good!
- [ ] The "fields" text should be black, currently is #333333
- [ ] The text size for all the text should be 14px (for wide screens) / 9 px for narrow screens (<= 495px wide) (right tnow the field text is correct size, only the non-field text needs updated)

**Comment by codemonkey800** [comment]
@liaprins-czi I think this one is fixed, could you check pls?

**Comment by liaprins-czi** [comment]
The fixes look good, but now there is something new happening that wasn't before: the spacing between each line is too tall.
_Here's how it should look:_
<img width="1415" alt="Field lists" src="https://user-images.githubusercontent.com/53277128/155405211-3ac2f4a0-bc16-4895-a621-f8d0b9f7201d.png">

_Here's how it looks now:_
<img width="361" alt="Screen Shot 2022-03-11 at 1 23 53 PM" src="https://user-images.githubusercontent.com/53277128/157970093-a54f7a27-87c8-49fd-91fa-496d843687a6.png">

**Comment by liaprins-czi** [comment]
This looks great to me! 🫶🪐
