### ISSUE TITLE
Add support for dropdown/accordion items in the theme

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari-sphinx-theme#7]
On the napari hub we have an accordion item we use to have expandable headers e.g. [the FAQ page](https://www.napari-hub.org/faq).

On napari.org we can currently use dropdown admonitions/"Click to show" features of JupyterBook, but these only apply to the executable documents.

It would be great if we could bring similarly styled accordion/dropdown items into the napari.org theme. Pinging @liaprins-czi on design and @codemonkey800 for implementation.

**Comment by melissawm** [comment]
We now have dropdowns from [sphinx-design](https://sphinx-design.readthedocs.io/en/latest/) and pydata-sphinx-theme.
