### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#71]
- [x] Find out if we are supposed to have an icon or image per page (basically why there is that little weird "missing image" sort of icon overlapping the first part of the text now (<img width="26" alt="Screen Shot 2022-02-17 at 9 05 06 AM" src="https://user-images.githubusercontent.com/53277128/154533140-8b999ac7-4142-4895-87c0-c3c382667a77.png">))
- [x] Design the way search results look

Here's what we get from PyData for free:
<img width="1185" alt="Screen Shot 2022-02-16 at 4 42 36 PM" src="https://user-images.githubusercontent.com/53277128/154532892-6333d86f-780d-46e9-a425-830edbcc48fa.png">

@codemonkey800 do you have any insight into what the little "missing image" icon that overlaps the text of search results is there for? <img width="26" alt="Screen Shot 2022-02-17 at 9 05 06 AM" src="https://user-images.githubusercontent.com/53277128/154533140-8b999ac7-4142-4895-87c0-c3c382667a77.png"> (e.g. is there a way to tell in the code, what it is trying unsuccessfully to point to?) Do you know if we need to supply some sort of icon or image? If so, should it map to some sort of category that each page falls into (in which case we should collectively think about those)?

**Comment by liaprins-czi** [comment]
Update: here's how it's supposed to look in PyData:
![image](https://user-images.githubusercontent.com/53277128/155395711-8694070b-a984-45ba-9450-1585aaeee608.png)

**Comment by liaprins-czi** [comment]
Here's the design for the search page in Figma:
https://www.figma.com/file/ahjEJjeaFL6oTjeQaueGDQ/napari-Sphinx-Theme?node-id=46%3A414

![Search results](https://user-images.githubusercontent.com/53277128/155433800-030db744-6fd9-498f-8a07-3fdb66b14e1b.png)

![Search results _ None](https://user-images.githubusercontent.com/53277128/155433820-ead2ac6a-63ea-4982-9418-d91976e5bce1.png)

A few things to note about the new design:
- It was very redundant to have the search bar in the left sidebar area _and_ in the main body copy area of the search page, ideally there'd only be the primary one in the main area of the page, so I removed the one from the left sidebar, only when on the search page (if not possible to do this for initially implementation, that's fine!)
- I also changed the position of the text saying how many results there are, to be immediately following the "Search results" heading
- Some of the text sizes and spacing updated
- No more line between each search result
- I think we can still use a little "document" icon per returned result, to indicate that it will take you to a page. I swapped in the ["document" icon I created for the hub's plugin pages](https://www.figma.com/file/pDKU0CdSzpSWGaoXXQVJLz/v0-hub-final-designs?node-id=21%3A953), so it better matches our look and feel. We don't need to have the bullet and the icon, though,that is too cluttery. So we just need the icon and not the bullet disc.

**Comment by liaprins-czi** [comment]
I love how this page is shaping up! There are just a couple of small things to update:

- [ ] Search icon should ideally be snugged up to the end of the search bar line, alignment-wise. Now it is indented slightly from the very end.
_What it looks like now:_
<img width="77" alt="Screen Shot 2022-02-28 at 4 44 48 PM" src="https://user-images.githubusercontent.com/53277128/156083514-b4852fb8-89da-499e-a0d3-2b3624a4513f.png">

_What it should look like:_
<img width="64" alt="Screen Shot 2022-02-28 at 4 49 11 PM" src="https://user-images.githubusercontent.com/53277128/156083617-35153a6e-384e-4444-b62b-c37642dd2d0f.png">

- [ ] 75px vertical spacing between bottom of results and top of footer (now there is not enough space)

- [ ] If possible to have the "x" take the place of the search icon when the result is loaded, then user can easily clear it if needed or change the input and then search icon would reappear in place of "x". (This one may be more tricky / time-consuming to implement, so no worries if it is, we don't have to worry about it now!)

- [ ] If possible, can the word "Results" and the following text about how many results were found (in a smaller typeface with lighter weight) share the same baseline? Right now they are center-aligned vertically, which makes the smaller text look like it is floating. Ideally they'd "sit" on the same level.
_What it looks like now:_
<img width="282" alt="Screen Shot 2022-02-28 at 4 43 51 PM" src="https://user-images.githubusercontent.com/53277128/156083373-b4d3fd68-f06e-41ac-912d-a135056a8c18.png">

**Comment by codemonkey800** [comment]
> If possible to have the "x" take the place of the search icon when the result is loaded, then user can easily clear it if needed or change the input and then search icon would reappear in place of "x". (This one may be more tricky / time-consuming to implement, so no worries if it is, we don't have to worry about it now!)

This will be time consuming because we're working around sphinx JS interactivity instead of building it out ourselves. Could you create a new issue for this one pls?

**Comment by liaprins-czi** [comment]
@codemonkey800 Does this issue I made yesterday cover it, or should there be another issue?
https://github.com/napari/napari-sphinx-theme/issues/82

**Comment by codemonkey800** [comment]
@liaprins-czi ooh good idea, let's use that for both search bars lol

**Comment by liaprins-czi** [comment]
Great, I have updated #82 to specify that it applies to both search bars!

**Comment by liaprins-czi** [comment]
This one looks good to me! 🥧🍕
