### ISSUE TITLE
Header clipping content

### ISSUE THREAD

**Issue by tlambert03** [napari/napari-sphinx-theme#76]
not sure if there's an open issue for this (feel free to close if so)

the header is clipping the content (this is scrolled all the way up)

<img width="1492" alt="Screen Shot 2022-03-01 at 12 26 45 PM" src="https://user-images.githubusercontent.com/1609449/156218169-32b40a15-d1cb-4e1e-9876-b49175b56c2b.png">

**Comment by codemonkey800** [comment]
haha thanks for reporting this, this got fixed in #77
