### ISSUE TITLE
Feature requests for calendar directive

### ISSUE THREAD

**Issue by jni** [napari/napari-sphinx-theme#78]
It's very exciting to have the calendar on the theme! 🎉 In the spirit of making the theme more widely applicable, I'd like to request the following improvements:

- [ ] rename the directive "calendar", since it could be any calendar. The fact that it's themed is implied by the use of the theme itself. 😂 
- [ ] make the calendar ID, which is public, a parameter of the directive, rather than created by an env var.
- [ ] (far future) allow non-Google calendar hosts (or are you using the Google CalDAV/.ics interface anyway?)

fwiw, I do have specific plans for this: I'd like to use the theme to make a homepage for imagesc-island, including an events calendar. 📆 🚀

**Comment by psobolewskiPhD** [comment]
I don't think the calendar is part of the theme anymore?
So I think this can be closed?
cc: @melissawm

**Comment by melissawm** [comment]
The calendar is now defined by https://fullcalendar.io/, with most of the scripting happening at https://github.com/napari/docs/blob/main/docs/community/meeting_schedule.md?plain=1

The styling, however, is mostly contained in the css on this repo. This is something I may want to revisit in the future to make it more organized...

If there are suggestions for calendar design or features/bugs, I'd prefer to keep them all at https://github.com/napari/napari-sphinx-theme/issues/78 just to make it easier to track, if possible.

**Comment by jni** [comment]
@melissawm so the main thing from the list above is a usage guide, maybe as part of development docs: how does access to the calendar work, which API is it using (CalDAV or GCal?), etc. It would be cool to have a demo site / blog post for how to make a nice calendar in a sphinx/myst site.

I want to move our calendar to the numfocus napari org so this will be good knowledge to have. 😅
