### ISSUE TITLE
Mimic hub search bar interaction

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari-sphinx-theme#82]
Ideally, we'd have the same behavior we have with the hub search bar: an ["x" icon](https://www.figma.com/file/NmdYwtpKfMzLnNLYYWrbTw/napari.org-final-designs?node-id=298%3A27) doesn't appear until the search results are displayed (in this case, on the search page), and the "x" would be in place of the magnifier. If the "x" is clicked, it clears the input and is replaced by the magnifier.

Note that this should apply to both the small search bar that appears in the top left of every page, as well as the search bar on the search page itself.

**Comment by melissawm** [comment]
Is this still something we want to do?

**Comment by psobolewskiPhD** [comment]
I don't think so?
Search on the napari-hub is more like a filter as far as I can tell.
Search on napari.org brings up a results page. So an x to clear wouldn't be useful?
Unless Im misunderstanding the behaviors...

**Comment by melissawm** [comment]
That's my thinking as well, and we can always revisit later but for now I will close. Feel free to reopen if you disagree.
