### ISSUE TITLE
Use true color for app bar

### ISSUE THREAD

**Issue by codemonkey800** [napari/napari-sphinx-theme#84]
@liaprins-czi  found a difference in the color presented in the browser version in Figma:
https://github.com/napari/napari-sphinx-theme/issues/45#issuecomment-1063223880

Issue seems to be that browser defaults to converting hex values into rgb values, so currently it's not possbile to use the *true* color: https://stackoverflow.com/a/39211005

There might be an opportunity to use new CSS syntax for color to achieve this:
https://css-tricks.com/new-css-color-features-preview/

**Comment by melissawm** [comment]
Probably not valid anymore - please reopen if that's not the case.
