### ISSUE TITLE
11px too small for narrow width

### ISSUE THREAD

**Issue by tlambert03** [napari/napari-sphinx-theme#87]
For me, the 11px used at narrow width is too small.

(header included for scale)

<img width="612" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/158493452-229398cb-c435-455c-b47f-0278c62136b7.png">

much prefer the ~15px used in the original pydata sphinx theme:
<img width="612" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/158493871-967c4cc8-5476-4e3a-aead-820b328e4309.png">

**Comment by codemonkey800** [comment]
curious to hear what @liaprins-czi thinks for this one, but it makes sense to me to increase the font size. however, lots of places use `11px` for the font size at smaller screens, so i wonder if we'll need to update the rest of the design too

**Comment by DragaDoncila** [comment]
I do tend to agree here that 11px looks a bit small. Idk if it's the font weight rather than the size, or maybe it's just the difference to the headers, but I do think it's a bit hard to read on mobile atm.

**Comment by liaprins-czi** [comment]
Thanks for the feedback, all! As Jeremy mentioned, this will affect the whole design, but it shouldn't be too hard to fix. Basically I will work on increasing the base text font size while maintaining the font scale (ratio of font sizes used across the design). @codemonkey800, @neuromusic and I are meeting tomorrow to triage bugs, including font size on mobile.

**Comment by psobolewskiPhD** [comment]
With #134 this can be closed. All the text is more readable and larger, particularly the API docs:
![image](https://github.com/napari/napari-sphinx-theme/assets/76622105/acda3414-2ba9-488f-845f-4f53a997f4a8)
