### ISSUE TITLE
Default Python syntax highlighting color is too faint

### ISSUE THREAD

**Issue by jni** [napari/napari-sphinx-theme#90]
The default color for syntax-highlighted Python code is absurdly faint, and makes the main body of code samples look greyed out and unimportant, when it is in fact the most important part.

![syntax](https://user-images.githubusercontent.com/492549/158762157-884098a8-cea9-4b58-8190-77da02c662d1.png)

(taken from napari/napari#4275)

imho the default color should be black or close to black.

**Comment by liaprins-czi** [comment]
The same code colors should be used as before, ideally. We made a custom color palette for the code colors so they would all be accessible. Here's a link to the design and colors:
https://www.figma.com/file/pDKU0CdSzpSWGaoXXQVJLz/?node-id=1010%3A93

**Comment by jni** [comment]
@liaprins-czi tbh I think that design offers too much colour variation and I find it extremely distracting. I think the community as a whole is moving to a more subtle touch with syntax highlighting, that turns out to be more readable and comprehensible. See for example [this recent blog post](https://අ.com/blog/syntax-highlighting/), or the default "light" scheme for VSCode:

<img width="560" alt="Screen Shot 2022-04-02 at 1 48 25 pm" src="https://user-images.githubusercontent.com/492549/161362922-2a960063-63c1-47fa-9e3f-143071f15fef.png">

**Comment by liaprins-czi** [comment]
We don't need to use all of the colors, those are just available. We can use only the first 3 or 4 or however many you all would prefer!

**Comment by jni** [comment]
First 4 would work great for me! 😊 Though personally I would darken the comments just a bit. But at this point I am indeed nitpicking, and that would be totally optional as far as I'm concerned.

I'm also ok with constants/literals of all types (string, number, boolean) being highlighted.

**Comment by jni** [comment]
Closed by #134 (!)
