### ISSUE TITLE
Listed maintainer in pyproject.toml should be updated

### ISSUE THREAD

**Issue by jni** [napari/napari-sphinx-theme#92]
The PyPI metadata still lists Joris Van den Bossche as a maintainer. That should probably be replaced with @codemonkey800 for example?

https://github.com/napari/napari-sphinx-theme/blob/e8ebbaa3b61e1b29fff9f6fd74530eca3d968fc5/pyproject.toml#L25

**Comment by codemonkey800** [comment]
ooh you got it, lots of little things we need to change like docs and package metadata. thanks for bringing this up

**Comment by psobolewskiPhD** [comment]
Was closed by https://github.com/napari/napari-sphinx-theme/pull/106
