### ISSUE TITLE
Possible issue with mobile viewport

### ISSUE THREAD

**Issue by tlambert03** [napari/napari-sphinx-theme#93]
I think there might be an issue on mobile: if you pinch/zoom out, the footer and the body no longer fill the viewport, there is a little extra padding on the right.

![image](https://user-images.githubusercontent.com/1609449/159391111-f5569ec4-7333-4362-87b9-dfc9ddc57ee9.png)

The pydata Sphinx theme doesn't seem to have the same issue

**Comment by codemonkey800** [comment]
@tlambert03 thank you for reporting this, this should be fixed now! please reopen if you encounter it again
