### ISSUE TITLE
Use version switcher from pydata-sphinx-theme

### ISSUE THREAD

**Issue by melissawm** [napari/napari-sphinx-theme#95]
The [pydata-sphinx-theme version switcher](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions) is [now live](https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.8.0)! You can see it in action here: https://scipy.github.io/devdocs/index.html

We could use it as-is, customizing the colors of the dropdown.

**Comment by jni** [comment]
So cool! Missed this when you first pinged @melissawm! What do you think are the odds of getting this in this coming week??? 😬

**Comment by melissawm** [comment]
Let me give it a go now!

**Comment by melissawm** [comment]
To use this, we want to have the previous documentation versions accessible somewhere. Could we do this in the napari.github.io repo? Do you folks have other ideas?

**Comment by jni** [comment]
Yes, we could retrospectively add past docs versions to vX.Y.Z/ folders on that repo. However, I'm also fine with only supporting future versions as a first step.
