### ISSUE TITLE
dropdown erroneously displays whitespace

### ISSUE THREAD

**Issue by kne42** [napari/napari-sphinx-theme#99]
## description

The dropdown admonition class erroneously displays whitespace while collapsed, causing it to look like there is no content present. Also, for user clarity, it should probably have an arrow to denote whether it is expanded or collapsed.

### collapsed

<img width="792" alt="Screen Shot 2022-05-07 at 10 54 57 AM" src="https://user-images.githubusercontent.com/29165011/167266082-5de76574-6b8b-48dd-9caf-a9e3562f6ff1.png">

### expanded

<img width="742" alt="Screen Shot 2022-05-07 at 10 57 54 AM" src="https://user-images.githubusercontent.com/29165011/167266203-5fa7e63f-5ebb-4a23-9a31-49c9e4238227.png">

### MyST Code

`````
````{admonition} **1. From pip**
:class: dropdown

napari can be installed on most macOS, Linux, and Windows systems with Python
3.7, 3.8, and 3.9 using pip:

```sh
python -m pip install "napari[all]"
```
You can then upgrade napari to a new version using

```sh
python -m pip install "napari[all]" --upgrade
```

*(See [Choosing a different Qt backend](#choosing-a-different-qt-backend) below for an explanation of the `[all]`
notation.)*

````
`````

**Comment by kne42** [comment]
cc @codemonkey800 this is a critical bug that will make it confusing to users trying to install napari

**Comment by kne42** [comment]
cc @liaprins-czi in case designs are needed for a dropdown style

**Comment by codemonkey800** [comment]
Interesting, this isn't reproducible in the docs site, but it is in napari.org. Need to check why only napari.org is having this issue 😆

**Comment by justinelarsen** [comment]
Same, I just discovered it and wasn't sure what was going on. I just so happen to click and saw more info, but was very confused.

**Comment by Czaki** [comment]
this problem with additional spaces comes from this line https://github.com/napari/napari-sphinx-theme/blob/86d9717b4e3607868ad53f5c2f49be12e3c67b8a/src/napari_sphinx_theme/assets/scss/components/page-content.scss#L401

**Comment by melissawm** [comment]
Probably was brought back when the docs for previous versions were built with the requirements of the time (previous version of the napari-sphinx-theme)

I can fix that manually, as I think this only shows up in this one page, right?

**Comment by melissawm** [comment]
I think this does it for the 0.4.16 version - let me know if you'd rather take a different approach @codemonkey800 !

**Comment by kandarpksk** [comment]
Maybe Peter's comment in #4911 is relevant to this?
https://github.com/napari/napari/issues/4911#issuecomment-1205896865

**Comment by psobolewskiPhD** [comment]
I can't reproduce this. Will close. If someone can reproduce, please re-open or make a new issue.
